Repository hyrise/hyrise, pull requests merged in 2018-10, with the labels that each got.

#1152 TPC-H Q1 date selection: filter on shipdate
  src/benchmarklib/tpch/tpch_queries.cpp
Labels: FullCI

#1106 Convert (NOT) EXISTS to semi/anti join
  src/lib/CMakeLists.txt
  src/lib/logical_query_plan/lqp_utils.hpp
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/strategy/column_pruning_rule.cpp
  src/lib/optimizer/strategy/column_pruning_rule.hpp
  src/lib/optimizer/strategy/exists_reformulation_rule.cpp
  src/lib/optimizer/strategy/exists_reformulation_rule.hpp
  src/lib/optimizer/strategy/predicate_pushdown_rule.cpp
  src/lib/statistics/table_statistics.cpp
  src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_nodes.hpp
  src/test/CMakeLists.txt
  src/test/optimizer/strategy/exists_reformulation_rule_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner_queries.sql
Labels: FullCI

#1156 Fix CMake warnings for empty add_library() call (#1147)
  src/plugins/CMakeLists.txt
Labels: FullCI

#1079 Multithreaded Benchmarks
  requirements.txt
  scripts/benchmark_multithreaded.py
  scripts/benchmark_tpcc.sh
  src/benchmark/tpch_benchmark.cpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_runner.hpp
  src/benchmarklib/benchmark_utils.cpp
  src/benchmarklib/benchmark_utils.hpp
  src/lib/scheduler/node_queue_scheduler.hpp
  src/lib/scheduler/topology.cpp
  src/lib/scheduler/topology.hpp
  src/lib/scheduler/worker.cpp
Labels: FullCI

#1162 Fix ExpressionResultNullableSeries::is_nullable()
  src/lib/expression/evaluation/expression_result_views.hpp
Labels: FullCI

#1118 Add histograms for segment statistics
  src/lib/CMakeLists.txt
  src/lib/expression/evaluation/like_matcher.cpp
  src/lib/expression/evaluation/like_matcher.hpp
  src/lib/optimizer/strategy/chunk_pruning_rule.cpp
  src/lib/statistics/chunk_statistics/abstract_filter.hpp
  src/lib/statistics/chunk_statistics/chunk_statistics.cpp
  src/lib/statistics/chunk_statistics/chunk_statistics.hpp
  src/lib/statistics/chunk_statistics/histograms/abstract_histogram.cpp
  src/lib/statistics/chunk_statistics/histograms/abstract_histogram.hpp
  src/lib/statistics/chunk_statistics/histograms/equal_distinct_count_histogram.cpp
  src/lib/statistics/chunk_statistics/histograms/equal_distinct_count_histogram.hpp
  src/lib/statistics/chunk_statistics/histograms/equal_height_histogram.cpp
  src/lib/statistics/chunk_statistics/histograms/equal_height_histogram.hpp
  src/lib/statistics/chunk_statistics/histograms/equal_width_histogram.cpp
  src/lib/statistics/chunk_statistics/histograms/equal_width_histogram.hpp
  src/lib/statistics/chunk_statistics/histograms/histogram_utils.cpp
  src/lib/statistics/chunk_statistics/histograms/histogram_utils.hpp
  src/lib/statistics/chunk_statistics/min_max_filter.hpp
  src/lib/statistics/chunk_statistics/range_filter.hpp
  src/lib/statistics/chunk_statistics/segment_statistics.cpp
  src/lib/statistics/chunk_statistics/segment_statistics.hpp
  src/lib/types.hpp
  src/test/CMakeLists.txt
  src/test/statistics/chunk_statistics/histograms/abstract_histogram_test.cpp
  src/test/statistics/chunk_statistics/histograms/equal_distinct_count_histogram_test.cpp
  src/test/statistics/chunk_statistics/histograms/equal_height_histogram_test.cpp
  src/test/statistics/chunk_statistics/histograms/equal_width_histogram_test.cpp
  src/test/statistics/chunk_statistics/histograms/histogram_utils_extended_test.cpp
  src/test/statistics/chunk_statistics/histograms/histogram_utils_test.cpp
  src/test/statistics/chunk_statistics/min_max_filter_test.cpp
  src/test/statistics/chunk_statistics/range_filter_test.cpp
  src/test/tables/float2.tbl
  src/test/tables/int_string_like_containing2.tbl
  src/test/tables/string2.tbl
  src/test/tables/string3.tbl
  src/test/tables/string_like_pruning.tbl
  src/test/tables/string_with_prefix.tbl
Labels: FullCI

#1157 Improve PredicateReorderingRule, fix MVCC bug in Projection
  src/lib/operators/projection.cpp
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/strategy/predicate_pushdown_rule.cpp
  src/lib/optimizer/strategy/predicate_reordering_rule.cpp
  src/test/operators/projection_test.cpp
Labels: FullCI

#1167 clang_tidy_wrapper: reference executable that actually exists.
  scripts/clang_tidy_wrapper.sh
Labels: FullCI

#1165 Removes SSE2-specific code from SIMD-BP128 implementation
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.cpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.hpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_iterator.hpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.cpp
Labels: FullCI, WIP

#1171 Fix Chunk Pruning for BETWEEN
  src/lib/expression/expression_functional.hpp
  src/lib/optimizer/strategy/chunk_pruning_rule.cpp
  src/lib/statistics/chunk_statistics/histograms/abstract_histogram.cpp
  src/test/expression/expression_evaluator_test.cpp
  src/test/expression/expression_test.cpp
  src/test/logical_query_plan/lqp_find_subplan_mismatch_test.cpp
  src/test/operators/operator_scan_predicate_test.cpp
  src/test/optimizer/lqp_translator_test.cpp
  src/test/optimizer/strategy/chunk_pruning_test.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI

#1163 Small performance improvements
  src/benchmarklib/tpch/tpch_db_generator.cpp
  src/lib/CMakeLists.txt
  src/lib/operators/aggregate.cpp
  src/lib/operators/aggregate.hpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/sort.cpp
  src/lib/operators/table_scan/base_single_column_table_scan_impl.cpp
  src/lib/storage/base_value_segment.hpp
  src/lib/storage/segment_iterables/chunk_offset_mapping.cpp
  src/lib/storage/segment_iterables/chunk_offset_mapping.hpp
  src/lib/storage/value_segment.cpp
  src/lib/storage/value_segment.hpp
  src/lib/utils/murmur_hash.cpp
  src/lib/utils/murmur_hash.hpp
Labels: FullCI

#1174 "Repair" pagination
  third_party/tpch-dbgen/dss.h
Labels: FullCI

#1175 Disable USDT in TSan builds
  src/lib/utils/tracing/probes.hpp
Labels: FullCI

#1177 Change default chunk size to 100,000 for benchmarks
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_utils.hpp
Labels: FullCI

#1176 Add functionality to create empty tables from meta info
  src/lib/import_export/csv_parser.cpp
  src/lib/import_export/csv_parser.hpp
  src/lib/utils/load_table.cpp
  src/lib/utils/load_table.hpp
  src/test/CMakeLists.txt
  src/test/lib/import_export/csv_parser_test.cpp
  src/test/lib/utils/load_table_test.cpp
Labels: FullCI

#1190 Fix ambiguous names in expression_functional.hpp
  src/lib/expression/expression_functional.cpp
  src/lib/expression/expression_functional.hpp
  src/lib/logical_query_plan/show_tables_node.cpp
  src/test/expression/expression_evaluator_test.cpp
  src/test/expression/expression_test.cpp
  src/test/expression/lqp_select_expression_test.cpp
  src/test/expression/pqp_select_expression_test.cpp
  src/test/logical_query_plan/aggregate_node_test.cpp
  src/test/logical_query_plan/join_node_test.cpp
  src/test/logical_query_plan/logical_query_plan_test.cpp
  src/test/logical_query_plan/mock_node_test.cpp
  src/test/operators/projection_test.cpp
  src/test/optimizer/lqp_translator_test.cpp
  src/test/optimizer/optimizer_test.cpp
  src/test/optimizer/strategy/exists_reformulation_rule_test.cpp
  src/test/optimizer/strategy/predicate_pushdown_rule_test.cpp
  src/test/sql/sql_identifier_resolver_test.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI

#1193 Add functionality to load and export binary files in console
  src/bin/console/console.cpp
  src/bin/console/console.hpp
Labels: FullCI

#1185 Prevent division by zero in BenchmarkRunner::_create_report().
  scripts/compare_benchmarks.py
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_utils.cpp
  src/benchmarklib/benchmark_utils.hpp
Labels: FullCI

#1191 Change execution time from us to ns, fix format_duration
  src/lib/sql/sql_pipeline.cpp
  src/lib/sql/sql_pipeline.hpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/lib/sql/sql_pipeline_statement.hpp
  src/lib/utils/format_duration.cpp
  src/test/base_test.hpp
  src/test/sql/sql_pipeline_statement_test.cpp
  src/test/sql/sql_pipeline_test.cpp
  src/test/utils/format_duration_test.cpp
Labels: FullCI

#1192 Fix SHOW COLUMNS
  src/lib/logical_query_plan/show_columns_node.cpp
  src/lib/logical_query_plan/show_columns_node.hpp
  src/test/logical_query_plan/show_columns_node_test.cpp
  src/test/logical_query_plan/show_tables_node_test.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI

#1196 Add help text for export command in console
  src/bin/console/console.cpp
Labels: FullCI

#1199 Fix nan issue in compare_benchmarks.py
  scripts/compare_benchmarks.py
Labels: FullCI

#1202 Change histogram utils string brute force tests
  src/test/CMakeLists.txt
  src/test/statistics/chunk_statistics/histograms/histogram_utils_extended_test.cpp
  src/test/statistics/chunk_statistics/histograms/histogram_utils_test.cpp
Labels: FullCI

#1204 Format ipp files and add functionality to only format git-staged files
  scripts/format.sh
Labels: FullCI

#1178 Support CREATE TABLE and DROP TABLE
  scripts/lint.sh
  src/lib/CMakeLists.txt
  src/lib/logical_query_plan/abstract_lqp_node.hpp
  src/lib/logical_query_plan/create_table_node.cpp
  src/lib/logical_query_plan/create_table_node.hpp
  src/lib/logical_query_plan/drop_table_node.cpp
  src/lib/logical_query_plan/drop_table_node.hpp
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/logical_query_plan/lqp_translator.hpp
  src/lib/operators/abstract_operator.hpp
  src/lib/operators/insert.cpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/maintenance/create_table.cpp
  src/lib/operators/maintenance/create_table.hpp
  src/lib/operators/maintenance/drop_table.cpp
  src/lib/operators/maintenance/drop_table.hpp
  src/lib/operators/table_scan.cpp
  src/lib/sql/sql_translator.cpp
  src/lib/sql/sql_translator.hpp
  src/test/CMakeLists.txt
  src/test/lib/import_export/csv_parser_test.cpp
  src/test/lib/utils/load_table_test.cpp
  src/test/logical_query_plan/create_table_node_test.cpp
  src/test/logical_query_plan/drop_table_node_test.cpp
  src/test/operators/insert_test.cpp
  src/test/operators/maintenance/create_table_test.cpp
  src/test/operators/maintenance/drop_table_test.cpp
  src/test/operators/table_scan_between_test.cpp
  src/test/optimizer/lqp_translator_test.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI

#1203 Try fixing TSan false positive
  src/lib/scheduler/abstract_task.cpp
  src/lib/utils/tracing/probes.hpp
Labels: FullCI

#1194 Prepare new CI
  Jenkinsfile
  src/bin/console/console.cpp
Labels: FullCI

#1198 Hash Join Improvements
  src/lib/CMakeLists.txt
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash.hpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/operators/join_hash/join_hash_traits.hpp
  src/test/CMakeLists.txt
  src/test/operators/join_equi_test.cpp
  src/test/operators/join_hash_test.cpp
  src/test/operators/join_hash_traits_test.cpp
  src/test/operators/join_hash_types_test.cpp
Labels: FullCI

#1216 Move unitialized_vector.hpp to third_party/
  src/lib/CMakeLists.txt
  src/lib/operators/join_hash/join_hash_steps.hpp
  third_party/CMakeLists.txt
  third_party/uninitialized_vector/uninitialized_vector.hpp
Labels: FullCI

#1217 Rename 'optimize' time to 'lqp translate' time
  src/lib/sql/sql_pipeline.cpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/lib/sql/sql_pipeline_statement.hpp
  src/test/sql/sql_pipeline_statement_test.cpp
  src/test/sql/sql_pipeline_test.cpp
Labels: FullCI

#1221 Fix CQF compilation on OS X
  src/lib/statistics/chunk_statistics/counting_quotient_filter.cpp
  src/lib/statistics/chunk_statistics/counting_quotient_filter.hpp
  src/test/statistics/chunk_statistics/counting_quotient_filter_test.cpp
Labels: FullCI

#1223 CI: Fix coverage comparison
  scripts/compare_coverage.sh
Labels: FullCI

#1226 Fix nan issue in compare_benchmarks.py
  scripts/compare_benchmarks.py
Labels: FullCI

#1227 Improve print testing
  src/lib/operators/print.cpp
  src/test/operators/print_test.cpp
Labels: FullCI

#1074 Coverage: Exclude files copied from LLVM
  scripts/coverage.sh
Labels: FullCI

#1234 Add new CI URL to README
  README.md
Labels: FullCI

#1213 BenchmarkRunner warmup runs
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_runner.hpp
  src/benchmarklib/benchmark_utils.cpp
  src/benchmarklib/benchmark_utils.hpp
Labels: FullCI

#1231 JoinGraphVisualizer
  src/benchmark/tpch_benchmark.cpp
  src/benchmarklib/benchmark_runner.cpp
  src/bin/CMakeLists.txt
  src/bin/console/console.cpp
  src/lib/CMakeLists.txt
  src/lib/logical_query_plan/lqp_utils.cpp
  src/lib/logical_query_plan/lqp_utils.hpp
  src/lib/optimizer/join_ordering/join_graph.cpp
  src/lib/optimizer/join_ordering/join_graph.hpp
  src/lib/optimizer/join_ordering/join_graph_builder.cpp
  src/lib/optimizer/strategy/join_ordering_rule.cpp
  src/lib/visualization/abstract_visualizer.hpp
  src/lib/visualization/join_graph_visualizer.cpp
  src/lib/visualization/join_graph_visualizer.hpp
  src/lib/visualization/lqp_visualizer.cpp
  src/lib/visualization/lqp_visualizer.hpp
  src/lib/visualization/sql_query_plan_visualizer.cpp
  src/lib/visualization/sql_query_plan_visualizer.hpp
  src/lib/visualization/viz_record_layout.cpp
  src/lib/visualization/viz_record_layout.hpp
  src/test/CMakeLists.txt
  src/test/logical_query_plan/lqp_utils_test.cpp
  src/test/optimizer/join_graph_builder_test.cpp
Labels: FullCI

#1210 Smart PosLists
  src/benchmark/operators/union_positions_benchmark.cpp
  src/lib/CMakeLists.txt
  src/lib/operators/delete.hpp
  src/lib/operators/difference.cpp
  src/lib/operators/index_scan.hpp
  src/lib/operators/insert.hpp
  src/lib/operators/join_index.cpp
  src/lib/operators/join_index.hpp
  src/lib/operators/join_nested_loop.cpp
  src/lib/operators/join_nested_loop.hpp
  src/lib/operators/sort.cpp
  src/lib/operators/table_scan.cpp
  src/lib/operators/table_scan/abstract_table_scan_impl.hpp
  src/lib/operators/table_scan/base_single_column_table_scan_impl.cpp
  src/lib/operators/table_scan/base_single_column_table_scan_impl.hpp
  src/lib/operators/table_scan/between_table_scan_impl.cpp
  src/lib/operators/table_scan/is_null_table_scan_impl.cpp
  src/lib/operators/table_scan/like_table_scan_impl.cpp
  src/lib/operators/table_scan/like_table_scan_impl.hpp
  src/lib/operators/table_scan/single_column_table_scan_impl.cpp
  src/lib/operators/union_positions.hpp
  src/lib/operators/validate.cpp
  src/lib/storage/dictionary_segment/attribute_vector_iterable.hpp
  src/lib/storage/dictionary_segment/dictionary_segment_iterable.hpp
  src/lib/storage/frame_of_reference/frame_of_reference_iterable.hpp
  src/lib/storage/materialize.hpp
  src/lib/storage/pos_list.hpp
  src/lib/storage/reference_segment.cpp
  src/lib/storage/reference_segment.hpp
  src/lib/storage/reference_segment/reference_segment_iterable.hpp
  src/lib/storage/run_length_segment/run_length_segment_iterable.hpp
  src/lib/storage/segment_accessor.hpp
  src/lib/storage/segment_iterables.hpp
  src/lib/storage/segment_iterables/any_segment_iterable.hpp
  src/lib/storage/segment_iterables/base_segment_iterators.hpp
  src/lib/storage/segment_iterables/chunk_offset_mapping.cpp
  src/lib/storage/segment_iterables/chunk_offset_mapping.hpp
  src/lib/storage/split_pos_list_by_chunk_id.cpp
  src/lib/storage/split_pos_list_by_chunk_id.hpp
  src/lib/storage/value_segment/null_value_vector_iterable.hpp
  src/lib/storage/value_segment/value_segment_iterable.hpp
  src/lib/types.hpp
  src/test/operators/union_positions_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
  src/test/storage/any_segment_iterable_test.cpp
  src/test/storage/encoded_segment_test.cpp
  src/test/storage/iterables_test.cpp
Labels: FullCI

#1237 Fix plan printing
  src/bin/console/console.cpp
Labels: FullCI

#1225 Aggregate: When adding a Projection before an Aggregate, don't add unused columns
  CONTRIBUTING.md
  src/lib/operators/aggregate.cpp
  src/lib/sql/sql_translator.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI

#1228 Scheduling rework & deadlock fix
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_runner.hpp
  src/lib/CMakeLists.txt
  src/lib/import_export/csv_parser.cpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_mpsm/column_materializer_numa.hpp
  src/lib/operators/join_mpsm/radix_cluster_sort_numa.hpp
  src/lib/scheduler/abstract_scheduler.hpp
  src/lib/scheduler/abstract_task.cpp
  src/lib/scheduler/abstract_task.hpp
  src/lib/scheduler/current_scheduler.hpp
  src/lib/scheduler/job_task.hpp
  src/lib/scheduler/node_queue_scheduler.cpp
  src/lib/scheduler/node_queue_scheduler.hpp
  src/lib/scheduler/operator_task.cpp
  src/lib/scheduler/processing_unit.cpp
  src/lib/scheduler/processing_unit.hpp
  src/lib/scheduler/task_queue.cpp
  src/lib/scheduler/task_queue.hpp
  src/lib/scheduler/worker.cpp
  src/lib/scheduler/worker.hpp
  src/lib/storage/storage_manager.cpp
  src/lib/tasks/migration_preparation_task.cpp
  src/lib/types.hpp
  src/test/scheduler/scheduler_test.cpp
Labels: FullCI

#1241 Readme: Fix sanitizer command
  README.md
Labels: FullCI

#1245 Reference Segment Iterator stores its accessor by Value - Fix bug #1244
  src/lib/storage/reference_segment/reference_segment_iterable.hpp
  src/test/storage/iterables_test.cpp
Labels: Bug, FullCI

#1248 Fix lint.sh
  scripts/lint.sh
Labels: FullCI

#1249 Disambiguate decoder/decompressor
  src/lib/storage/dictionary_segment.cpp
  src/lib/storage/dictionary_segment.hpp
  src/lib/storage/dictionary_segment/attribute_vector_iterable.hpp
  src/lib/storage/dictionary_segment/dictionary_segment_iterable.hpp
  src/lib/storage/fixed_string_dictionary_segment.cpp
  src/lib/storage/fixed_string_dictionary_segment.hpp
  src/lib/storage/frame_of_reference/frame_of_reference_encoder.hpp
  src/lib/storage/frame_of_reference/frame_of_reference_iterable.hpp
  src/lib/storage/frame_of_reference_segment.cpp
  src/lib/storage/frame_of_reference_segment.hpp
  src/lib/storage/index/group_key/composite_group_key_index.cpp
  src/lib/storage/vector_compression/base_compressed_vector.hpp
  src/lib/storage/vector_compression/base_vector_compressor.hpp
  src/lib/storage/vector_compression/fixed_size_byte_aligned/fixed_size_byte_aligned_compressor.cpp
  src/lib/storage/vector_compression/fixed_size_byte_aligned/fixed_size_byte_aligned_compressor.hpp
  src/lib/storage/vector_compression/fixed_size_byte_aligned/fixed_size_byte_aligned_vector.hpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.cpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.hpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_decompressor.cpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_decompressor.hpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_vector.cpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_vector.hpp
  src/lib/storage/vector_compression/vector_compression.cpp
  src/lib/storage/vector_compression/vector_compression.hpp
  src/test/storage/compressed_vector_test.cpp
  src/test/storage/simd_bp128_test.cpp
Labels: FullCI
