Repository hyrise/hyrise, pull requests merged in 2018-07, with the labels that each got.

#943 Selective CI
  Jenkinsfile
  scripts/current_branch_has_pull_request_label.py
Labels: FullCI

#961 Fix clang-tidy relying on version number
  Jenkinsfile
  install.sh
  src/lib/tasks/chunk_metrics_collection_task.cpp
Labels: FullCI

#953 coverage with clang
  DEPENDENCIES.md
  Dockerfile
  Jenkinsfile
  scripts/coverage.sh
Labels: FullCI

#952 Avoid jobs without work load in join hash
  src/lib/operators/join_hash.cpp
Labels: FullCI

#956 Fix unencoded TPCH Benchmarks
  Jenkinsfile
  src/lib/statistics/chunk_statistics/chunk_column_statistics.cpp
  src/lib/statistics/chunk_statistics/chunk_column_statistics.hpp
  src/lib/storage/chunk.cpp
  src/lib/storage/chunk.hpp
  src/lib/storage/chunk_encoder.cpp
Labels: FullCI

#948 Use DataType Enum in EncodingConfig
  src/benchmarklib/benchmark_utils.cpp
  src/benchmarklib/benchmark_utils.hpp
Labels: FullCI

#967 Fixed coverage percentage calculation
  scripts/coverage.sh
Labels: FullCI

#958 Store IDs instead of AllTypeVariants in the AggregateKey
  src/lib/operators/aggregate.cpp
  src/lib/operators/aggregate.hpp
Labels: FullCI

#896 Refactor exception handling
  src/bin/console/console.cpp
  src/lib/sql/hsql_expr_translator.cpp
  src/lib/sql/sql_pipeline.cpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/lib/sql/sql_translator.cpp
  src/lib/utils/assert.hpp
  src/lib/utils/invalid_input_exception.hpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI

#971 Make Topology a singleton (and fix the topology representation for non-NUMA systems)
  src/benchmarklib/benchmark_runner.cpp
  src/bin/console/console.cpp
  src/bin/server.cpp
  src/lib/CMakeLists.txt
  src/lib/scheduler/abstract_scheduler.cpp
  src/lib/scheduler/abstract_scheduler.hpp
  src/lib/scheduler/node_queue_scheduler.cpp
  src/lib/scheduler/node_queue_scheduler.hpp
  src/lib/scheduler/topology.cpp
  src/lib/scheduler/topology.hpp
  src/lib/storage/numa_placement_manager.cpp
  src/lib/storage/numa_placement_manager.hpp
  src/lib/tasks/migration_preparation_task.cpp
  src/lib/types.hpp
  src/test/operators/import_csv_test.cpp
  src/test/scheduler/scheduler_test.cpp
  src/test/server/server_test_runner.cpp
  src/test/sql/sql_pipeline_statement_test.cpp
  src/test/sql/sql_pipeline_test.cpp
  src/test/sql/sql_query_plan_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
  src/test/storage/numa_placement_test.cpp
Labels: Concurrency/Scheduling, FullCI, Refactor

#973 Fix stupid race condition
  src/lib/concurrency/commit_context.cpp
  src/test/server/server_test_runner.cpp
Labels: FullCI

#969 Add MPSM Join with fixed sanitizer issues on non-NUMA systems
  src/benchmark/operators/join_benchmark.cpp
  src/benchmarklib/benchmark_runner.cpp
  src/lib/CMakeLists.txt
  src/lib/operators/abstract_operator.hpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_mpsm.hpp
  src/lib/operators/join_mpsm/column_materializer_numa.hpp
  src/lib/operators/join_mpsm/radix_cluster_sort_numa.hpp
  src/lib/scheduler/node_queue_scheduler.cpp
  src/lib/scheduler/topology.cpp
  src/lib/scheduler/topology.hpp
  src/lib/storage/numa_placement_manager.cpp
  src/lib/storage/numa_placement_manager.hpp
  src/lib/tasks/chunk_migration_task.cpp
  src/lib/tasks/migration_preparation_task.cpp
  src/test/operators/import_csv_test.cpp
  src/test/operators/join_equi_test.cpp
  src/test/operators/join_null_test.cpp
  src/test/operators/recreation_test.cpp
  src/test/scheduler/scheduler_test.cpp
  src/test/sql/sql_pipeline_statement_test.cpp
  src/test/sql/sql_pipeline_test.cpp
  src/test/sql/sql_query_plan_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
  src/test/storage/numa_placement_test.cpp
Labels: FullCI, Operator

#977 Fix included cpps
  scripts/lint.sh
  src/lib/operators/join_mpsm/column_materializer_numa.hpp
  src/test/logical_query_plan/union_node_test.cpp
  src/test/operators/jit_operator_wrapper_test.cpp
  src/test/server/server_session_test.cpp
Labels: FullCI

#979 Mp18/radix bits
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash.hpp
  src/test/operators/join_equi_test.cpp
Labels: FullCI

#982 Remove some shared_ptrs where they are not needed
  src/lib/operators/aggregate.cpp
  src/lib/operators/join_hash.cpp
  src/lib/utils/cuckoo_hashtable.hpp
  src/test/utils/cuckoo_hashtable_test.cpp
Labels: FullCI

#990 Fix SQLiteWrapper returning empty table if last char is a newline
  src/test/sql/sqlite_testrunner/sqlite_wrapper.cpp
Labels: FullCI

#992 Disable NUMAPlacementTest
  src/test/storage/numa_placement_test.cpp
Labels: FullCI

#993 Small jenkins and install.sh improvements
  Jenkinsfile
  install.sh
Labels: FullCI

#998 Fix AggregateTest
  src/test/operators/aggregate_test.cpp
Labels: FullCI

#1001 Fix: Only index.html coverage file is generated
  Jenkinsfile
Labels: FullCI

#995 vector::reserve() in JoinHash
  src/lib/operators/join_hash.cpp
  src/lib/statistics/generate_column_statistics.cpp
Labels: FullCI, WIP

#1004 type_cast without throw
  src/lib/type_cast.hpp
Labels: FullCI

#983 Add tsan to sanitization phase
  .tsan-ignore.txt
  CMakeLists.txt
  Jenkinsfile
  README.md
  src/lib/scheduler/abstract_task.cpp
  src/lib/scheduler/abstract_task.hpp
Labels: FullCI, WIP

#1011 Remove BaseColumn::visit
  src/lib/CMakeLists.txt
  src/lib/operators/aggregate.cpp
  src/lib/operators/aggregate.hpp
  src/lib/operators/export_binary.cpp
  src/lib/operators/export_binary.hpp
  src/lib/operators/export_csv.hpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_sort_merge.cpp
  src/lib/operators/table_scan/base_single_column_table_scan_impl.cpp
  src/lib/operators/table_scan/base_single_column_table_scan_impl.hpp
  src/lib/operators/table_scan/is_null_table_scan_impl.cpp
  src/lib/operators/table_scan/is_null_table_scan_impl.hpp
  src/lib/operators/table_scan/like_table_scan_impl.cpp
  src/lib/operators/table_scan/like_table_scan_impl.hpp
  src/lib/operators/table_scan/single_column_table_scan_impl.cpp
  src/lib/operators/table_scan/single_column_table_scan_impl.hpp
  src/lib/storage/abstract_column_visitor.hpp
  src/lib/storage/base_column.hpp
  src/lib/storage/base_dictionary_column.cpp
  src/lib/storage/base_dictionary_column.hpp
  src/lib/storage/base_encoded_column.cpp
  src/lib/storage/base_encoded_column.hpp
  src/lib/storage/column_visitable.hpp
  src/lib/storage/reference_column.cpp
  src/lib/storage/reference_column.hpp
  src/lib/storage/value_column.cpp
  src/lib/storage/value_column.hpp
Labels: FullCI

#1010 Use size_t for to store string lengths in table binary files
  src/lib/operators/export_binary.cpp
  src/lib/operators/export_binary.hpp
  src/lib/operators/import_binary.cpp
  src/lib/operators/import_binary.hpp
  src/lib/storage/table_column_definition.cpp
  src/lib/storage/value_column.cpp
  src/lib/types.hpp
  src/test/binary/AllTypesDictionaryColumn.bin
  src/test/binary/AllTypesDictionaryNullValues.bin
  src/test/binary/AllTypesMixColumn.bin
  src/test/binary/AllTypesNullValues.bin
  src/test/binary/AllTypesValueColumn.bin
  src/test/binary/AllTypesValueColumnMaxChunkSize.bin
  src/test/binary/EmptyStringsDictionaryColumn.bin
  src/test/binary/EmptyStringsValueColumn.bin
  src/test/binary/InvalidAttributeVectorWidth.bin
  src/test/binary/InvalidColumnType.bin
  src/test/binary/MultipleChunkSingleFloatColumn.bin
  src/test/binary/SingleChunkSingleFloatColumn.bin
  src/test/binary/StringDictionaryColumn.bin
  src/test/binary/StringValueColumn.bin
  src/test/binary/TwoColumnsNoValues.bin
  src/test/binary/float.bin
  src/test/storage/table_test.cpp
  src/test/storage/value_column_test.cpp
Labels: FullCI

#1009 Avoid empty sort merge join jobs
  src/lib/operators/join_sort_merge.cpp
Labels: Concurrency/Scheduling, FullCI

#1000 Fix Scheduler deadlock and race condition
  src/lib/import_export/csv_parser.cpp
  src/lib/operators/index_scan.cpp
  src/lib/operators/index_scan.hpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_mpsm/column_materializer_numa.hpp
  src/lib/operators/join_mpsm/radix_cluster_sort_numa.hpp
  src/lib/operators/join_sort_merge/column_materializer.hpp
  src/lib/scheduler/abstract_scheduler.hpp
  src/lib/scheduler/abstract_task.cpp
  src/lib/scheduler/abstract_task.hpp
  src/lib/scheduler/job_task.hpp
  src/lib/scheduler/node_queue_scheduler.hpp
  src/lib/scheduler/operator_task.cpp
  src/lib/scheduler/operator_task.hpp
  src/lib/scheduler/processing_unit.cpp
  src/lib/scheduler/processing_unit.hpp
  src/lib/scheduler/task_queue.cpp
  src/lib/scheduler/task_queue.hpp
  src/lib/scheduler/worker.cpp
  src/lib/scheduler/worker.hpp
  src/lib/tasks/chunk_migration_task.cpp
  src/lib/tasks/chunk_migration_task.hpp
  src/lib/tasks/migration_preparation_task.cpp
  src/lib/types.hpp
  src/test/sql/sqlite_testrunner/sqlite_wrapper.cpp
Labels: Concurrency/Scheduling, FullCI

#1013 Reduce the number of TPC-H hacks
  src/benchmarklib/tpch/tpch_queries.cpp
Labels: FullCI

#994 Use monotonic_buffer_resource for Aggregate
  src/lib/CMakeLists.txt
  src/lib/operators/aggregate.cpp
  src/lib/operators/aggregate.hpp
  src/lib/utils/aligned_size.hpp
Labels: FullCI

#1015 Make clang-tidy a bit happier
  .clang-tidy
  .clang-tidy-ignore
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/expression/evaluation/expression_evaluator.hpp
  src/lib/expression/expression_utils.cpp
  src/lib/expression/expression_utils.hpp
  src/lib/logical_query_plan/abstract_lqp_node.cpp
  src/lib/logical_query_plan/abstract_lqp_node.hpp
  src/lib/operators/abstract_operator.cpp
  src/lib/operators/abstract_operator.hpp
  src/lib/operators/difference.cpp
  src/lib/operators/difference.hpp
  src/lib/operators/insert.cpp
  src/lib/operators/jit_operator/jit_aware_lqp_translator.cpp
  src/lib/operators/jit_operator/jit_aware_lqp_translator.hpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_nested_loop.hpp
  src/lib/operators/join_sort_merge.cpp
  src/lib/operators/limit.cpp
  src/lib/operators/limit.hpp
  src/lib/operators/print.cpp
  src/lib/operators/print.hpp
  src/lib/operators/projection.cpp
  src/lib/operators/projection.hpp
  src/lib/operators/sort.cpp
  src/lib/operators/sort.hpp
  src/lib/operators/table_scan.cpp
  src/lib/operators/table_scan.hpp
  src/lib/operators/table_scan/base_single_column_table_scan_impl.cpp
  src/lib/operators/table_scan/base_single_column_table_scan_impl.hpp
  src/lib/operators/table_scan/is_null_table_scan_impl.cpp
  src/lib/optimizer/strategy/abstract_rule.cpp
  src/lib/optimizer/strategy/chunk_pruning_rule.hpp
  src/lib/optimizer/strategy/index_scan_rule.cpp
  src/lib/optimizer/strategy/index_scan_rule.hpp
  src/lib/planviz/lqp_visualizer.cpp
  src/lib/scheduler/abstract_task.cpp
  src/lib/scheduler/node_queue_scheduler.cpp
  src/lib/scheduler/topology.hpp
  src/lib/server/client_connection.cpp
  src/lib/server/client_connection.hpp
  src/lib/server/query_response_builder.cpp
  src/lib/server/query_response_builder.hpp
  src/lib/server/server_session.cpp
  src/lib/server/server_session.hpp
  src/lib/sql/parameter_id_allocator.hpp
  src/lib/sql/sql_pipeline_builder.cpp
  src/lib/sql/sql_pipeline_builder.hpp
  src/lib/sql/sql_query_plan.cpp
  src/lib/sql/sql_query_plan.hpp
  src/lib/sql/sql_translator.cpp
  src/lib/sql/sql_translator.hpp
  src/lib/statistics/base_column_statistics.hpp
  src/lib/statistics/column_statistics.cpp
  src/lib/statistics/column_statistics.hpp
  src/lib/statistics/generate_table_statistics.cpp
  src/lib/statistics/statistics_import_export.hpp
  src/test/logical_query_plan/lqp_find_subplan_mismatch_test.cpp
Labels: FullCI
