Repository hyrise/hyrise, pull requests merged in 2019-09, with the labels that each got.

#1831 Update md5 hash of IMDB data
  scripts/setup_imdb.py
Labels: FullCI, ReallyEasyToReview

#1825 Benchmark: Only add SQLite data if the dedicated result set is incomplete
  src/benchmark/join_order_benchmark.cpp
  src/benchmark/tpcds_benchmark.cpp
  src/benchmarklib/abstract_benchmark_item_runner.cpp
  src/benchmarklib/abstract_benchmark_item_runner.hpp
  src/benchmarklib/benchmark_runner.cpp
Labels: FullCI, Masterprojekt, ReallyEasyToReview

#1834 Update multi-predicate-join comment
  src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp
Labels: FullCI

#1800 Null-aware Single Segment Indexes
  resources/test_data/tbl/join_operators/int_outer_join_null.tbl
  src/lib/CMakeLists.txt
  src/lib/operators/index_scan.cpp
  src/lib/operators/join_index.cpp
  src/lib/operators/join_index.hpp
  src/lib/storage/chunk.cpp
  src/lib/storage/chunk.hpp
  src/lib/storage/index/abstract_index.cpp
  src/lib/storage/index/abstract_index.hpp
  src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_index.cpp
  src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_index.hpp
  src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_nodes.cpp
  src/lib/storage/index/b_tree/b_tree_index.cpp
  src/lib/storage/index/b_tree/b_tree_index.hpp
  src/lib/storage/index/b_tree/b_tree_index_impl.cpp
  src/lib/storage/index/b_tree/b_tree_index_impl.hpp
  src/lib/storage/index/base_index.cpp
  src/lib/storage/index/group_key/composite_group_key_index.cpp
  src/lib/storage/index/group_key/composite_group_key_index.hpp
  src/lib/storage/index/group_key/group_key_index.cpp
  src/lib/storage/index/group_key/group_key_index.hpp
  src/test/base_test.hpp
  src/test/operators/join_index_test.cpp
  src/test/storage/adaptive_radix_tree_index_test.cpp
  src/test/storage/btree_index_test.cpp
  src/test/storage/group_key_index_test.cpp
  src/test/storage/multi_segment_index_test.cpp
  src/test/storage/single_segment_index_test.cpp
Labels: Feature, FullCI, Test/Benchmark

#1828 Join Predicate Ordering Rule
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/tpcds/tpcds_table_generator.cpp
  src/benchmarklib/tpcds/tpcds_table_generator.hpp
  src/lib/CMakeLists.txt
  src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/strategy/join_predicate_ordering_rule.cpp
  src/lib/optimizer/strategy/join_predicate_ordering_rule.hpp
  src/lib/optimizer/strategy/subquery_to_join_rule.cpp
  src/lib/statistics/cardinality_estimator.cpp
  src/test/CMakeLists.txt
  src/test/base_test.hpp
  src/test/concurrency/transaction_context_test.cpp
  src/test/optimizer/strategy/join_predicate_ordering_rule_test.cpp
  src/test/optimizer/strategy/subquery_to_join_rule_test.cpp
  src/test/tpc/tpcds_db_generator_test.cpp
Labels: FullCI

#1836 Add const LQP support to visit_lqp() and clean up LQP hashing
  src/lib/logical_query_plan/abstract_lqp_node.cpp
  src/lib/logical_query_plan/abstract_lqp_node.hpp
  src/lib/logical_query_plan/lqp_utils.hpp
  src/test/logical_query_plan/aggregate_node_test.cpp
  src/test/logical_query_plan/alias_node_test.cpp
  src/test/logical_query_plan/create_prepared_plan_node_test.cpp
  src/test/logical_query_plan/create_table_node_test.cpp
  src/test/logical_query_plan/create_view_node_test.cpp
  src/test/logical_query_plan/delete_node_test.cpp
  src/test/logical_query_plan/drop_table_node_test.cpp
  src/test/logical_query_plan/drop_view_node_test.cpp
  src/test/logical_query_plan/dummy_table_node_test.cpp
  src/test/logical_query_plan/insert_node_test.cpp
  src/test/logical_query_plan/join_node_test.cpp
  src/test/logical_query_plan/limit_node_test.cpp
  src/test/logical_query_plan/mock_node_test.cpp
  src/test/logical_query_plan/predicate_node_test.cpp
  src/test/logical_query_plan/projection_node_test.cpp
  src/test/logical_query_plan/sort_node_test.cpp
  src/test/logical_query_plan/static_table_node_test.cpp
  src/test/logical_query_plan/stored_table_node_test.cpp
  src/test/logical_query_plan/union_node_test.cpp
  src/test/logical_query_plan/update_node_test.cpp
  src/test/logical_query_plan/validate_node_test.cpp
  src/test/storage/table_column_definition_test.cpp
Labels: FullCI

#1781 ExpressionEvaluator: Cache expressions
  src/lib/expression/abstract_expression.cpp
  src/lib/expression/abstract_expression.hpp
  src/lib/expression/abstract_predicate_expression.cpp
  src/lib/expression/abstract_predicate_expression.hpp
  src/lib/expression/aggregate_expression.cpp
  src/lib/expression/aggregate_expression.hpp
  src/lib/expression/arithmetic_expression.cpp
  src/lib/expression/arithmetic_expression.hpp
  src/lib/expression/binary_predicate_expression.cpp
  src/lib/expression/binary_predicate_expression.hpp
  src/lib/expression/case_expression.cpp
  src/lib/expression/case_expression.hpp
  src/lib/expression/cast_expression.cpp
  src/lib/expression/cast_expression.hpp
  src/lib/expression/correlated_parameter_expression.cpp
  src/lib/expression/correlated_parameter_expression.hpp
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/expression/evaluation/expression_evaluator.hpp
  src/lib/expression/exists_expression.cpp
  src/lib/expression/exists_expression.hpp
  src/lib/expression/extract_expression.cpp
  src/lib/expression/extract_expression.hpp
  src/lib/expression/function_expression.cpp
  src/lib/expression/function_expression.hpp
  src/lib/expression/list_expression.cpp
  src/lib/expression/list_expression.hpp
  src/lib/expression/logical_expression.cpp
  src/lib/expression/logical_expression.hpp
  src/lib/expression/lqp_column_expression.cpp
  src/lib/expression/lqp_column_expression.hpp
  src/lib/expression/lqp_subquery_expression.cpp
  src/lib/expression/lqp_subquery_expression.hpp
  src/lib/expression/placeholder_expression.cpp
  src/lib/expression/placeholder_expression.hpp
  src/lib/expression/pqp_column_expression.cpp
  src/lib/expression/pqp_column_expression.hpp
  src/lib/expression/pqp_subquery_expression.cpp
  src/lib/expression/pqp_subquery_expression.hpp
  src/lib/expression/unary_minus_expression.cpp
  src/lib/expression/unary_minus_expression.hpp
  src/lib/expression/value_expression.cpp
  src/lib/expression/value_expression.hpp
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/strong_typedef.hpp
  src/test/expression/expression_evaluator_to_values_test.cpp
  src/test/expression/expression_test.cpp
  src/test/expression/pqp_subquery_expression_test.cpp
  src/test/logical_query_plan/lqp_translator_test.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI

#1833 Optimize Validate operator to validate chunks in parallel
  src/lib/operators/validate.cpp
  src/lib/operators/validate.hpp
Labels: FullCI, Masterprojekt, Performance

#1817 New Rule: Rewrite IN expressions to disjunctions or joins
  src/lib/CMakeLists.txt
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/expression/lqp_column_expression.cpp
  src/lib/logical_query_plan/static_table_node.cpp
  src/lib/logical_query_plan/static_table_node.hpp
  src/lib/logical_query_plan/union_node.cpp
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/strategy/expression_reduction_rule.cpp
  src/lib/optimizer/strategy/expression_reduction_rule.hpp
  src/lib/optimizer/strategy/in_expression_rewrite_rule.cpp
  src/lib/optimizer/strategy/in_expression_rewrite_rule.hpp
  src/test/CMakeLists.txt
  src/test/expression/expression_test.cpp
  src/test/optimizer/strategy/expression_reduction_rule_test.cpp
  src/test/optimizer/strategy/in_expression_rewrite_rule_test.cpp
Labels: FullCI

#1806 Semi Join Reduction
  src/lib/logical_query_plan/abstract_lqp_node.cpp
  src/lib/logical_query_plan/abstract_lqp_node.hpp
  src/lib/optimizer/strategy/subquery_to_join_rule.cpp
  src/lib/visualization/lqp_visualizer.cpp
  src/test/optimizer/strategy/subquery_to_join_rule_test.cpp
Labels: FullCI

#1804 New rule: Rewrite AVG if SUM and COUNT are known
  src/lib/expression/expression_utils.cpp
  src/lib/expression/expression_utils.hpp
  src/lib/logical_query_plan/abstract_lqp_node.cpp
  src/lib/logical_query_plan/lqp_utils.hpp
  src/lib/optimizer/strategy/expression_reduction_rule.cpp
  src/lib/optimizer/strategy/expression_reduction_rule.hpp
  src/test/expression/expression_utils_test.cpp
  src/test/logical_query_plan/logical_query_plan_test.cpp
  src/test/logical_query_plan/lqp_utils_test.cpp
  src/test/optimizer/strategy/expression_reduction_rule_test.cpp
Labels: FullCI

#1837 Treat semi join reductions as predicates (adds estimation for semi joins)
  src/lib/logical_query_plan/lqp_utils.cpp
  src/lib/logical_query_plan/lqp_utils.hpp
  src/lib/optimizer/strategy/predicate_reordering_rule.cpp
  src/lib/statistics/cardinality_estimator.cpp
  src/lib/statistics/cardinality_estimator.hpp
  src/test/optimizer/strategy/join_predicate_ordering_rule_test.cpp
  src/test/statistics/cardinality_estimator_test.cpp
Labels: FullCI

#1841 Fix chunk size in benchmarks, add join side in viz
  Jenkinsfile
  scripts/test/hyriseBenchmarkTPCH_test.py
  src/benchmarklib/abstract_table_generator.cpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp
  src/lib/visualization/abstract_visualizer.hpp
  src/lib/visualization/lqp_visualizer.cpp
  src/lib/visualization/lqp_visualizer.hpp
  src/lib/visualization/pqp_visualizer.cpp
  src/lib/visualization/pqp_visualizer.hpp
Labels: FullCI

#1838 Adapt table generator
  src/benchmark/micro_benchmark_basic_fixture.cpp
  src/benchmark/operators/difference_benchmark.cpp
  src/benchmark/operators/join_benchmark.cpp
  src/benchmark/operators/projection_benchmark.cpp
  src/benchmark/operators/table_scan_benchmark.cpp
  src/benchmark/operators/table_scan_sorted_benchmark.cpp
  src/benchmark/operators/union_all_benchmark.cpp
  src/benchmarklib/CMakeLists.txt
  src/benchmarklib/synthetic_table_generator.cpp
  src/benchmarklib/synthetic_table_generator.hpp
  src/benchmarklib/table_generator.cpp
  src/benchmarklib/table_generator.hpp
Labels: FullCI

#1812 Incorporate Singletons to Hyrise object
  src/benchmark/file_based_benchmark.cpp
  src/benchmark/join_order_benchmark.cpp
  src/benchmark/tpcds_benchmark.cpp
  src/benchmark/tpch_benchmark.cpp
  src/benchmark/tpch_data_micro_benchmark.cpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_runner.hpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp
  src/bin/console/console.cpp
  src/bin/server.cpp
  src/lib/CMakeLists.txt
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/hyrise.cpp
  src/lib/hyrise.hpp
  src/lib/import_export/csv_parser.cpp
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/index_scan.cpp
  src/lib/operators/jit_operator/specialization/jit_code_specializer.cpp
  src/lib/operators/jit_operator/specialization/jit_code_specializer.hpp
  src/lib/operators/jit_operator/specialization/jit_repository.cpp
  src/lib/operators/jit_operator/specialization/jit_repository.hpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_mpsm/column_materializer_numa.hpp
  src/lib/operators/join_mpsm/radix_cluster_sort_numa.hpp
  src/lib/operators/join_sort_merge.cpp
  src/lib/operators/join_sort_merge/column_materializer.hpp
  src/lib/operators/join_sort_merge/radix_cluster_sort.hpp
  src/lib/operators/table_scan.cpp
  src/lib/operators/validate.cpp
  src/lib/scheduler/abstract_scheduler.hpp
  src/lib/scheduler/abstract_task.cpp
  src/lib/scheduler/abstract_task.hpp
  src/lib/scheduler/current_scheduler.cpp
  src/lib/scheduler/current_scheduler.hpp
  src/lib/scheduler/immediate_execution_scheduler.cpp
  src/lib/scheduler/immediate_execution_scheduler.hpp
  src/lib/scheduler/node_queue_scheduler.cpp
  src/lib/scheduler/node_queue_scheduler.hpp
  src/lib/scheduler/topology.cpp
  src/lib/scheduler/topology.hpp
  src/lib/scheduler/worker.cpp
  src/lib/scheduler/worker.hpp
  src/lib/server/task_runner.hpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/lib/storage/storage_manager.cpp
  src/lib/tasks/server/bind_server_prepared_statement_task.cpp
  src/lib/tasks/server/execute_server_prepared_statement_task.cpp
  src/plugins/CMakeLists.txt
  src/test/base_test.hpp
  src/test/operators/import_csv_test.cpp
  src/test/operators/jit_operator/specialization/jit_code_specializer_test.cpp
  src/test/operators/operator_deep_copy_test.cpp
  src/test/scheduler/scheduler_test.cpp
  src/test/server/server_test_runner.cpp
  src/test/sql/sql_pipeline_statement_test.cpp
  src/test/sql/sql_pipeline_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.hpp
Labels: FullCI

#1842 Two expression resolution fixes in SQLTranslator
  src/lib/expression/expression_utils.hpp
  src/lib/sql/sql_identifier_resolver.cpp
  src/lib/sql/sql_identifier_resolver.hpp
  src/lib/sql/sql_translator.cpp
  src/test/sql/sql_identifier_resolver_test.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI, ReallyEasyToReview

#1847 Sub-Plan Memoization Test
  src/test/logical_query_plan/lqp_translator_test.cpp
Labels: FullCI, Masterprojekt, ReallyEasyToReview

#1848 Fix performance regression in JOB
  src/lib/operators/table_scan/column_like_table_scan_impl.cpp
Labels: FullCI

#1846 Clean up hyriseSystemTest and unify encoding enumerations
  Jenkinsfile
  src/lib/storage/encoding_type.hpp
  src/test/base_test.hpp
  src/test/operators/join_test_runner.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner_encodings.cpp
  src/test/storage/any_segment_iterable_test.cpp
  src/test/storage/encoded_segment_test.cpp
  src/test/storage/encoded_string_segment_test.cpp
  src/test/storage/encoding_test.hpp
  src/test/storage/materialize_test.cpp
  src/test/storage/segment_iterators_test.cpp
Labels: FullCI

#1855 Run chunk pruning after between composition
  src/lib/optimizer/optimizer.cpp
Labels: FullCI, ReallyEasyToReview

#1861 Make DisjunctionStrategy test deterministic
  src/test/optimizer/strategy/in_expression_rewrite_rule_test.cpp
Labels: FullCI

#1862 Add new plotting scripts
  requirements.txt
  scripts/compare_benchmarks.py
  scripts/plot_performance_breakdown.py
  scripts/plot_performance_over_commit_range.py
  scripts/plot_run_duration_over_time.py
  src/benchmarklib/benchmark_runner.cpp
Labels: FullCI

#1853 Subquery in arithmetic expression to Join
  src/lib/optimizer/strategy/join_predicate_ordering_rule.hpp
  src/lib/optimizer/strategy/subquery_to_join_rule.cpp
  src/test/optimizer/strategy/subquery_to_join_rule_test.cpp
Labels: FullCI, Masterprojekt, Optimizer, Performance

#1856 Faster synthetic table creation
  src/benchmark/tpch_data_micro_benchmark.cpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/synthetic_table_generator.cpp
  src/benchmarklib/synthetic_table_generator.hpp
  src/lib/constant_mappings.cpp
  src/lib/constant_mappings.hpp
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/hyrise.cpp
  src/lib/hyrise.hpp
  src/lib/import_export/csv_parser.cpp
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/index_scan.cpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_mpsm/column_materializer_numa.hpp
  src/lib/operators/join_mpsm/radix_cluster_sort_numa.hpp
  src/lib/operators/join_sort_merge.cpp
  src/lib/operators/join_sort_merge/column_materializer.hpp
  src/lib/operators/join_sort_merge/radix_cluster_sort.hpp
  src/lib/operators/table_scan.cpp
  src/lib/operators/validate.cpp
  src/lib/scheduler/abstract_task.cpp
  src/lib/scheduler/abstract_task.hpp
  src/lib/scheduler/worker.cpp
  src/lib/server/task_runner.hpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/lib/storage/chunk_encoder.cpp
  src/lib/storage/chunk_encoder.hpp
  src/lib/storage/encoding_type.hpp
  src/lib/storage/lz4_segment.cpp
  src/lib/storage/lz4_segment/lz4_encoder.hpp
  src/lib/storage/storage_manager.cpp
  src/lib/tasks/server/execute_server_prepared_statement_task.cpp
  src/test/CMakeLists.txt
  src/test/base_test.hpp
  src/test/operators/import_csv_test.cpp
  src/test/operators/operator_deep_copy_test.cpp
  src/test/scheduler/scheduler_test.cpp
  src/test/storage/chunk_encoder_test.cpp
  src/test/storage/compressed_vector_test.cpp
  src/test/synthetic_table_generator_test.cpp
Labels: FullCI

#1863 Better estimation for correlated parameters
  src/lib/expression/expression_utils.cpp
  src/lib/expression/expression_utils.hpp
  src/lib/sql/sql_translator.cpp
  src/lib/statistics/cardinality_estimator.cpp
  src/test/expression/expression_utils_test.cpp
  src/test/statistics/cardinality_estimator_test.cpp
Labels: FullCI

#1865 Make left/right side of joins deterministic
  src/lib/logical_query_plan/mock_node.cpp
  src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp
  src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.hpp
  src/test/logical_query_plan/create_prepared_plan_node_test.cpp
  src/test/logical_query_plan/create_view_node_test.cpp
  src/test/logical_query_plan/mock_node_test.cpp
  src/test/optimizer/dp_ccp_test.cpp
  src/test/optimizer/greedy_operator_ordering_test.cpp
  src/test/optimizer/join_graph_test.cpp
  src/test/optimizer/strategy/join_ordering_rule_test.cpp
Labels: FullCI, ReallyEasyToReview

#1866 Forward a chunk's ordered-by information to GetTable
  src/benchmarklib/abstract_table_generator.cpp
  src/lib/operators/get_table.cpp
  src/test/operators/get_table_test.cpp
Labels: FullCI, ReallyEasyToReview

#1858 Improve doc wording in Optimizer and StorageManager
  src/lib/optimizer/optimizer.cpp
  src/lib/storage/storage_manager.cpp
Labels: FullCI
