Repository hyrise/hyrise, pull requests merged in 2019-05, with the labels that each got.

#1636 Support IF NOT EXISTS in CREATE TABLE and CREATE VIEW
  src/lib/logical_query_plan/create_table_node.cpp
  src/lib/logical_query_plan/create_table_node.hpp
  src/lib/logical_query_plan/create_view_node.cpp
  src/lib/logical_query_plan/create_view_node.hpp
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/operators/maintenance/create_table.cpp
  src/lib/operators/maintenance/create_table.hpp
  src/lib/operators/maintenance/create_view.cpp
  src/lib/operators/maintenance/create_view.hpp
  src/lib/sql/sql_translator.cpp
  src/test/logical_query_plan/create_table_node_test.cpp
  src/test/logical_query_plan/create_view_node_test.cpp
  src/test/logical_query_plan/lqp_translator_test.cpp
  src/test/operators/maintenance/create_table_test.cpp
  src/test/operators/maintenance/create_view_test.cpp
  src/test/sql/sql_translator_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
Labels: FullCI

#1614 Upgrade CI to Ubuntu 19.04, clang 7
  .clang-tidy
  CMakeLists.txt
  DEPENDENCIES.md
  Dockerfile
  Jenkinsfile
  README.md
  install.sh
  resources/.valgrind-ignore.txt
  scripts/coverage.sh
  scripts/format.sh
  src/CMakeLists.txt
  src/benchmark/file_based_benchmark.cpp
  src/benchmark/join_order_benchmark.cpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/cli_config_parser.cpp
  src/benchmarklib/file_based_query_generator.cpp
  src/benchmarklib/file_based_table_generator.cpp
  src/benchmarklib/tpch/tpch_table_generator.cpp
  src/bin/console/console.cpp
  src/bin/console/pagination.cpp
  src/lib/CMakeLists.txt
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/difference.cpp
  src/lib/operators/jit_operator/jit_types.cpp
  src/lib/operators/jit_operator/operators/jit_expression.cpp
  src/lib/operators/jit_operator/specialization/jit_code_specializer.cpp
  src/lib/operators/jit_operator/specialization/jit_code_specializer.hpp
  src/lib/operators/jit_operator/specialization/jit_compiler.cpp
  src/lib/operators/jit_operator/specialization/jit_compiler.hpp
  src/lib/operators/jit_operator/specialization/jit_repository.cpp
  src/lib/operators/jit_operator/specialization/jit_repository.hpp
  src/lib/operators/jit_operator/specialization/llvm/CloneFunction.cpp
  src/lib/operators/jit_operator/specialization/llvm/CloneFunction.diff
  src/lib/operators/jit_operator/specialization/llvm/InlineFunction.cpp
  src/lib/operators/jit_operator/specialization/llvm/InlineFunction.diff
  src/lib/operators/jit_operator/specialization/llvm/README.md
  src/lib/operators/jit_operator/specialization/llvm_extensions.hpp
  src/lib/statistics/chunk_statistics/histograms/equal_width_histogram.cpp
  src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_index.cpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.cpp
  src/lib/utils/filesystem.hpp
  src/lib/utils/plugin_manager.cpp
  src/lib/utils/plugin_manager.hpp
  src/lib/utils/string_utils.cpp
  src/lib/utils/string_utils.hpp
  src/plugins/CMakeLists.txt
  src/test/CMakeLists.txt
  src/test/gtest_main.cpp
  src/test/operators/jit_operator/specialization/resolve_condition_test.cpp
  src/test/storage/storage_manager_test.cpp
  src/test/utils/plugin_manager_test.cpp
  src/test/utils/singleton_test.cpp
Labels: FullCI

#1651 Hyrise Console Test
  Dockerfile
  Jenkinsfile
  install.sh
  requirements.txt
  scripts/planviz/is_iterm2.sh
  scripts/test/hyriseConsole_test.py
Labels: FullCI

#1633 RFC: Erase iterators/accessors depending on compile-time setting
  src/lib/CMakeLists.txt
  src/lib/storage/create_iterable_from_segment.hpp
  src/lib/storage/reference_segment/reference_segment_iterable.hpp
Labels: FullCI

#1660 Enforce clang 7.0 and gcc 8.2
  CMakeLists.txt
  DEPENDENCIES.md
  scripts/coverage.sh
Labels: FullCI

#1661 Rely less on Table::append_chunk()
  src/lib/operators/abstract_join_operator.cpp
  src/lib/operators/abstract_join_operator.hpp
  src/lib/operators/alias_operator.cpp
  src/lib/operators/difference.cpp
  src/lib/operators/get_table.cpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_index.cpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_nested_loop.cpp
  src/lib/operators/join_sort_merge.cpp
  src/lib/operators/join_verification.cpp
  src/lib/operators/limit.cpp
  src/lib/operators/product.cpp
  src/lib/operators/projection.cpp
  src/lib/operators/table_scan.cpp
  src/lib/operators/union_all.cpp
  src/lib/operators/validate.cpp
  src/lib/storage/chunk.cpp
  src/lib/storage/chunk.hpp
  src/lib/storage/table.cpp
  src/lib/storage/table.hpp
  src/test/operators/jit_operator/operators/jit_read_write_tuple_test.cpp
  src/test/operators/jit_operator/operators/jit_write_reference_test.cpp
  src/test/operators/validate_test.cpp
  src/test/storage/segment_accessor_test.cpp
Labels: FullCI

#1665 Fix issue with empty string vectors and FixedStringVector
  src/lib/storage/dictionary_segment/dictionary_encoder.hpp
  src/lib/storage/fixed_string_dictionary_segment.cpp
  src/lib/storage/fixed_string_dictionary_segment/fixed_string_vector.cpp
  src/lib/storage/fixed_string_dictionary_segment/fixed_string_vector.hpp
  src/test/storage/encoded_string_segment_test.cpp
  src/test/storage/fixed_string_vector_test.cpp
Labels: FullCI

#1667 Use JoinOperator::supports() to find a matching Join implementation for a JoinNode
  resources/test_data/sqlite_testrunner_queries.sql
  src/lib/logical_query_plan/lqp_translator.cpp
  src/test/logical_query_plan/lqp_translator_test.cpp
Labels: FullCI

#1669 Fix static compiler choice for jemalloc
  third_party/CMakeLists.txt
Labels: FullCI

#1664 Perform column pruning in GetTable/StoredTableNode
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/logical_query_plan/mock_node.cpp
  src/lib/logical_query_plan/mock_node.hpp
  src/lib/logical_query_plan/stored_table_node.cpp
  src/lib/logical_query_plan/stored_table_node.hpp
  src/lib/operators/get_table.cpp
  src/lib/operators/get_table.hpp
  src/lib/optimizer/strategy/chunk_pruning_rule.cpp
  src/lib/optimizer/strategy/chunk_pruning_rule.hpp
  src/lib/optimizer/strategy/column_pruning_rule.cpp
  src/lib/storage/chunk.cpp
  src/lib/storage/table.cpp
  src/test/logical_query_plan/create_prepared_plan_node_test.cpp
  src/test/logical_query_plan/create_view_node_test.cpp
  src/test/logical_query_plan/logical_query_plan_test.cpp
  src/test/logical_query_plan/mock_node_test.cpp
  src/test/logical_query_plan/stored_table_node_test.cpp
  src/test/operators/delete_test.cpp
  src/test/operators/get_table_test.cpp
  src/test/optimizer/join_graph_test.cpp
  src/test/optimizer/strategy/chunk_pruning_test.cpp
  src/test/optimizer/strategy/column_pruning_rule_test.cpp
  src/test/storage/storage_manager_test.cpp
Labels: FullCI

#1657 Enable re-encoding of segments
  src/benchmark/operators/table_scan_sorted_benchmark.cpp
  src/lib/operators/abstract_operator.cpp
  src/lib/storage/base_segment.hpp
  src/lib/storage/base_segment_encoder.hpp
  src/lib/storage/chunk_encoder.cpp
  src/lib/storage/chunk_encoder.hpp
  src/lib/storage/dictionary_segment/dictionary_encoder.hpp
  src/lib/storage/encoding_type.hpp
  src/lib/storage/fixed_string_dictionary_segment/fixed_string_vector.hpp
  src/lib/storage/frame_of_reference_segment/frame_of_reference_encoder.hpp
  src/lib/storage/lz4_segment/lz4_encoder.hpp
  src/lib/storage/run_length_segment/run_length_encoder.hpp
  src/lib/storage/segment_encoding_utils.cpp
  src/lib/storage/segment_encoding_utils.hpp
  src/lib/utils/check_table_equal.cpp
  src/lib/utils/check_table_equal.hpp
  src/lib/visualization/pqp_visualizer.cpp
  src/test/base_test.hpp
  src/test/storage/any_segment_iterable_test.cpp
  src/test/storage/chunk_encoder_test.cpp
  src/test/storage/chunk_test.cpp
  src/test/storage/dictionary_segment_test.cpp
  src/test/storage/encoded_segment_test.cpp
  src/test/storage/encoded_string_segment_test.cpp
  src/test/storage/fixed_string_dictionary_segment_test.cpp
  src/test/storage/lz4_segment_test.cpp
  src/test/storage/segment_accessor_test.cpp
  src/test/testing_assert.hpp
Labels: FullCI

#1675 Adapt supported encodings of FoR
  src/lib/storage/encoding_type.hpp
  src/lib/storage/frame_of_reference_segment.cpp
  src/test/operators/join_test_runner.cpp
Labels: FullCI

#1676 Make slack notification more stable
  Jenkinsfile
Labels: FullCI

#1597 BenchmarkRunner: Run items, not queries
  scripts/benchmark_multithreaded.py
  scripts/compare_benchmarks.py
  scripts/cpplint.py
  src/benchmark/file_based_benchmark.cpp
  src/benchmark/join_order_benchmark.cpp
  src/benchmark/tpch_benchmark.cpp
  src/benchmarklib/CMakeLists.txt
  src/benchmarklib/abstract_benchmark_item_runner.cpp
  src/benchmarklib/abstract_benchmark_item_runner.hpp
  src/benchmarklib/abstract_query_generator.cpp
  src/benchmarklib/abstract_query_generator.hpp
  src/benchmarklib/abstract_table_generator.cpp
  src/benchmarklib/benchmark_config.cpp
  src/benchmarklib/benchmark_config.hpp
  src/benchmarklib/benchmark_item_result.cpp
  src/benchmarklib/benchmark_item_result.hpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_runner.hpp
  src/benchmarklib/benchmark_sql_executor.cpp
  src/benchmarklib/benchmark_sql_executor.hpp
  src/benchmarklib/cli_config_parser.cpp
  src/benchmarklib/file_based_benchmark_item_runner.cpp
  src/benchmarklib/file_based_benchmark_item_runner.hpp
  src/benchmarklib/query_benchmark_result.cpp
  src/benchmarklib/query_benchmark_result.hpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.hpp
  src/benchmarklib/tpch/tpch_query_generator.hpp
  src/benchmarklib/tpch/tpch_table_generator.cpp
  src/bin/CMakeLists.txt
  src/bin/console/console.cpp
  src/bin/tpch_table_generator.cpp
  src/lib/scheduler/abstract_scheduler.hpp
  src/lib/scheduler/current_scheduler.cpp
  src/lib/scheduler/current_scheduler.hpp
  src/lib/scheduler/node_queue_scheduler.cpp
  src/lib/scheduler/node_queue_scheduler.hpp
  src/lib/sql/sql_pipeline.cpp
  src/lib/sql/sql_pipeline.hpp
  src/lib/storage/storage_manager.cpp
  src/lib/storage/storage_manager.hpp
  src/lib/visualization/abstract_visualizer.hpp
  src/test/tpc/tpch_test.cpp
Labels: FullCI

#1683 Remove Space after Comma in SUBSTR Column
  src/lib/expression/function_expression.cpp
  src/test/expression/expression_test.cpp
Labels: FullCI, Masterprojekt

#1631 Force pipeline users to deal with transaction aborts
  scripts/lint.sh
  src/benchmarklib/benchmark_sql_executor.cpp
  src/benchmarklib/benchmark_sql_executor.hpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp
  src/bin/console/console.cpp
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/expression/evaluation/like_matcher.cpp
  src/lib/operators/jit_operator/operators/jit_read_tuples.cpp
  src/lib/operators/join_sort_merge/radix_cluster_sort.hpp
  src/lib/operators/sort.cpp
  src/lib/server/server_session.cpp
  src/lib/sql/sql_pipeline.cpp
  src/lib/sql/sql_pipeline.hpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/lib/sql/sql_pipeline_statement.hpp
  src/lib/statistics/chunk_statistics/histograms/equal_distinct_count_histogram.cpp
  src/lib/statistics/chunk_statistics/histograms/equal_height_histogram.cpp
  src/lib/statistics/chunk_statistics/histograms/equal_width_histogram.cpp
  src/lib/storage/frame_of_reference_segment/frame_of_reference_encoder.hpp
  src/test/operators/operator_deep_copy_test.cpp
  src/test/server/server_session_test.cpp
  src/test/sql/sql_pipeline_statement_test.cpp
  src/test/sql/sql_pipeline_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
  src/test/tpc/tpch_test.cpp
Labels: FullCI

#1615 Make Logical and Physical Plan caches non-global
  src/benchmark/operators/sql_benchmark.cpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_runner.hpp
  src/bin/console/console.cpp
  src/bin/console/console.hpp
  src/lib/cache/cache.hpp
  src/lib/sql/sql_pipeline.cpp
  src/lib/sql/sql_pipeline.hpp
  src/lib/sql/sql_pipeline_builder.cpp
  src/lib/sql/sql_pipeline_builder.hpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/lib/sql/sql_pipeline_statement.hpp
  src/test/base_test.hpp
  src/test/operators/join_test_runner.cpp
  src/test/server/server_test_runner.cpp
  src/test/sql/query_plan_cache_test.cpp
  src/test/sql/sql_pipeline_statement_test.cpp
  src/test/sql/sql_pipeline_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
  src/test/storage/fixed_string_vector_test.cpp
  src/test/tpc/tpch_test.cpp
Labels: FullCI

#1685 Add information on supported compiler versions
  README.md
Labels: FullCI

#1689 Console: Survive missing tables in DML
  src/lib/sql/sql_translator.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI

#1599 [JIT] Remove necessity to access nullable information in JitAwareLQPTranslator
  src/lib/logical_query_plan/jit_aware_lqp_translator.cpp
  src/lib/logical_query_plan/jit_aware_lqp_translator.hpp
  src/lib/operators/jit_operator/jit_operations.cpp
  src/lib/operators/jit_operator/jit_operations.hpp
  src/lib/operators/jit_operator/jit_types.cpp
  src/lib/operators/jit_operator/jit_types.hpp
  src/lib/operators/jit_operator/operators/abstract_jittable.hpp
  src/lib/operators/jit_operator/operators/jit_aggregate.cpp
  src/lib/operators/jit_operator/operators/jit_aggregate.hpp
  src/lib/operators/jit_operator/operators/jit_compute.cpp
  src/lib/operators/jit_operator/operators/jit_compute.hpp
  src/lib/operators/jit_operator/operators/jit_expression.cpp
  src/lib/operators/jit_operator/operators/jit_expression.hpp
  src/lib/operators/jit_operator/operators/jit_filter.cpp
  src/lib/operators/jit_operator/operators/jit_filter.hpp
  src/lib/operators/jit_operator/operators/jit_read_tuples.cpp
  src/lib/operators/jit_operator/operators/jit_read_tuples.hpp
  src/lib/operators/jit_operator/operators/jit_validate.cpp
  src/lib/operators/jit_operator/operators/jit_validate.hpp
  src/lib/operators/jit_operator/operators/jit_write_tuples.cpp
  src/lib/operators/jit_operator/operators/jit_write_tuples.hpp
  src/lib/operators/jit_operator_wrapper.cpp
  src/test/logical_query_plan/jit_aware_lqp_translator_test.cpp
  src/test/operators/jit_operator/jit_hashmap_entry_test.cpp
  src/test/operators/jit_operator/jit_operations_test.cpp
  src/test/operators/jit_operator/jit_tuple_entry_test.cpp
  src/test/operators/jit_operator/operators/jit_aggregate_test.cpp
  src/test/operators/jit_operator/operators/jit_compute_test.cpp
  src/test/operators/jit_operator/operators/jit_expression_test.cpp
  src/test/operators/jit_operator/operators/jit_filter_test.cpp
  src/test/operators/jit_operator/operators/jit_read_write_tuple_test.cpp
  src/test/operators/jit_operator/operators/jit_validate_test.cpp
  src/test/operators/jit_operator_wrapper_test.cpp
Labels: FullCI

#1681 Verification: Case Insensitive Column Name Comparison
  src/lib/utils/check_table_equal.cpp
  src/test/CMakeLists.txt
  src/test/lib/utils/verify_tables_test.cpp
Labels: FullCI, Masterprojekt

#1695 Add master project team to the contributors
  README.md
Labels: FullCI, Masterprojekt, ReallyEasyToReview
