Repository hyrise/hyrise, pull requests merged in 2019-11, with the labels that each got.

#1882 Optimizing Validation: validating entire chunks
  Jenkinsfile
  resources/test_data/tbl/meta_tables/meta_chunks_updated.tbl
  resources/test_data/tbl/meta_tables/meta_segments_updated.tbl
  resources/test_data/tbl/meta_tables/meta_tables_updated.tbl
  src/benchmarklib/abstract_table_generator.cpp
  src/benchmarklib/synthetic_table_generator.cpp
  src/lib/concurrency/transaction_context.cpp
  src/lib/concurrency/transaction_context.hpp
  src/lib/operators/get_table.cpp
  src/lib/operators/insert.cpp
  src/lib/operators/projection.cpp
  src/lib/operators/validate.cpp
  src/lib/operators/validate.hpp
  src/lib/storage/chunk.cpp
  src/lib/storage/chunk.hpp
  src/lib/storage/chunk_encoder.cpp
  src/lib/storage/mvcc_data.hpp
  src/lib/storage/table.cpp
  src/lib/storage/table.hpp
  src/lib/utils/load_table.cpp
  src/test/lib/utils/load_table_test.cpp
  src/test/operators/export_binary_test.cpp
  src/test/operators/get_table_test.cpp
  src/test/operators/import_binary_test.cpp
  src/test/operators/insert_test.cpp
  src/test/operators/projection_test.cpp
  src/test/operators/table_scan_between_test.cpp
  src/test/operators/table_scan_test.cpp
  src/test/operators/validate_test.cpp
  src/test/optimizer/strategy/chunk_pruning_rule_test.cpp
  src/test/storage/chunk_encoder_test.cpp
  src/test/storage/chunk_test.cpp
  src/test/storage/table_test.cpp
  src/test/tasks/chunk_compression_task_test.cpp
Labels: FullCI

#1907 Fix LQP outputs
  resources/test_data/sqlite_testrunner_queries.sql
  src/lib/logical_query_plan/lqp_column_reference.cpp
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/optimizer.hpp
  src/lib/sql/sql_pipeline.cpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/test/operators/operator_deep_copy_test.cpp
  src/test/optimizer/optimizer_test.cpp
  src/test/optimizer/strategy/join_ordering_rule_test.cpp
Labels: FullCI

#1868 Hyrise server
  README.md
  scripts/lint.sh
  src/bin/server.cpp
  src/lib/CMakeLists.txt
  src/lib/server/client_connection.cpp
  src/lib/server/client_connection.hpp
  src/lib/server/client_disconnect_exception.hpp
  src/lib/server/postgres_message_type.hpp
  src/lib/server/postgres_protocol_handler.cpp
  src/lib/server/postgres_protocol_handler.hpp
  src/lib/server/postgres_wire_handler.cpp
  src/lib/server/postgres_wire_handler.hpp
  src/lib/server/query_handler.cpp
  src/lib/server/query_handler.hpp
  src/lib/server/query_response_builder.cpp
  src/lib/server/query_response_builder.hpp
  src/lib/server/read_buffer.cpp
  src/lib/server/read_buffer.hpp
  src/lib/server/result_serializer.cpp
  src/lib/server/result_serializer.hpp
  src/lib/server/ring_buffer_iterator.hpp
  src/lib/server/server.cpp
  src/lib/server/server.hpp
  src/lib/server/server_session.cpp
  src/lib/server/server_session.hpp
  src/lib/server/session.cpp
  src/lib/server/session.hpp
  src/lib/server/task_runner.hpp
  src/lib/server/then_operator.hpp
  src/lib/server/use_boost_future.hpp
  src/lib/server/use_boost_future_impl.hpp
  src/lib/server/write_buffer.cpp
  src/lib/server/write_buffer.hpp
  src/lib/tasks/server/abstract_server_task.hpp
  src/lib/tasks/server/bind_server_prepared_statement_task.cpp
  src/lib/tasks/server/bind_server_prepared_statement_task.hpp
  src/lib/tasks/server/create_pipeline_task.cpp
  src/lib/tasks/server/create_pipeline_task.hpp
  src/lib/tasks/server/execute_server_prepared_statement_task.cpp
  src/lib/tasks/server/execute_server_prepared_statement_task.hpp
  src/lib/tasks/server/execute_server_query_task.cpp
  src/lib/tasks/server/execute_server_query_task.hpp
  src/lib/tasks/server/load_server_file_task.cpp
  src/lib/tasks/server/load_server_file_task.hpp
  src/lib/tasks/server/parse_server_prepared_statement_task.cpp
  src/lib/tasks/server/parse_server_prepared_statement_task.hpp
  src/lib/types.hpp
  src/test/CMakeLists.txt
  src/test/server/mock_connection.hpp
  src/test/server/mock_socket.hpp
  src/test/server/mock_task_runner.hpp
  src/test/server/postgres_protocol_handler_test.cpp
  src/test/server/postgres_wire_handler_test.cpp
  src/test/server/query_handler_test.cpp
  src/test/server/read_buffer_test.cpp
  src/test/server/result_serializer_test.cpp
  src/test/server/server_session_test.cpp
  src/test/server/server_test_runner.cpp
  src/test/server/write_buffer_test.cpp
  src/test/tasks/load_server_file_task_test.cpp
Labels: FullCI, Refactor

#1911 Update clang-tidy-ignore
  .clang-tidy-ignore
Labels: FullCI, ReallyEasyToReview

#1906 Modifications to LZ4 iterable
  src/lib/storage/lz4_segment/lz4_segment_iterable.hpp
Labels: FullCI

#1918 Missing compression in chunk pruning tests
  src/test/optimizer/strategy/chunk_pruning_rule_test.cpp
Labels: FullCI

#1917 Make return types a little bit more consistent.
  src/lib/import_export/csv_parser.cpp
  src/lib/logical_query_plan/stored_table_node.cpp
  src/lib/operators/get_table.cpp
  src/lib/sql/sql_translator.cpp
  src/lib/statistics/cardinality_estimator.cpp
  src/lib/statistics/table_statistics.cpp
  src/lib/storage/chunk.cpp
  src/lib/storage/chunk.hpp
  src/lib/storage/chunk_encoder.cpp
  src/lib/storage/table.cpp
  src/lib/storage/table.hpp
  src/lib/types.hpp
  src/lib/utils/sqlite_wrapper.cpp
  src/test/server/server_test_runner.cpp
Labels: FullCI, ReallyEasyToReview, Refactor

#1909 Fix multi-threading in GetTable, add conflict test
  .clang-tidy
  resources/.tsan-ignore.txt
  src/benchmark/tpch_benchmark.cpp
  src/benchmarklib/abstract_table_generator.cpp
  src/benchmarklib/benchmark_item_result.hpp
  src/benchmarklib/tpcc/tpcc_table_generator.hpp
  src/lib/import_export/csv_converter.hpp
  src/lib/operators/abstract_operator.cpp
  src/lib/operators/delete.cpp
  src/lib/operators/delete.hpp
  src/lib/operators/get_table.cpp
  src/lib/operators/get_table.hpp
  src/lib/operators/import_binary.cpp
  src/lib/operators/index_scan.cpp
  src/lib/operators/insert.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/operators/join_index.cpp
  src/lib/operators/join_sort_merge.cpp
  src/lib/server/result_serializer.cpp
  src/lib/storage/chunk.cpp
  src/lib/storage/chunk.hpp
  src/lib/storage/mvcc_data.cpp
  src/lib/storage/mvcc_data.hpp
  src/lib/storage/table.cpp
  src/lib/storage/table.hpp
  src/lib/storage/value_segment.hpp
  src/lib/visualization/abstract_visualizer.hpp
  src/test/CMakeLists.txt
  src/test/concurrency/stress_test.cpp
  src/test/operators/delete_test.cpp
  src/test/operators/get_table_test.cpp
  src/test/operators/print_test.cpp
  src/test/operators/union_positions_test.cpp
  src/test/operators/update_test.cpp
  src/test/server/server_test_runner.cpp
  src/test/storage/table_test.cpp
Labels: FullCI

#1924 A potpourri of smaller fixes
  install.sh
  scripts/format.sh
  scripts/test/hyriseBenchmarkFileBased_test.py
  scripts/test/hyriseBenchmarkJoinOrder_test.py
  scripts/test/hyriseBenchmarkTPCH_test.py
  src/benchmarklib/benchmark_sql_executor.cpp
  src/benchmarklib/benchmark_sql_executor.hpp
  src/benchmarklib/cli_config_parser.cpp
  src/lib/operators/abstract_read_write_operator.cpp
  src/lib/operators/abstract_read_write_operator.hpp
  src/lib/optimizer/strategy/in_expression_rewrite_rule.cpp
  src/lib/statistics/cardinality_estimator.cpp
  src/test/optimizer/strategy/in_expression_rewrite_rule_test.cpp
  src/test/statistics/cardinality_estimator_test.cpp
Labels: FullCI, ReallyEasyToReview

#1927 Benchmark: make --runs default to infinity
  scripts/test/hyriseBenchmarkTPCH_test.py
  src/benchmarklib/benchmark_config.cpp
  src/benchmarklib/benchmark_config.hpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/cli_config_parser.cpp
Labels: FullCI

#1854 Refactor ColumnPruningRule, add basic constraints
  resources/test_data/sqlite_testrunner_queries.sql
  src/benchmarklib/abstract_table_generator.cpp
  src/benchmarklib/abstract_table_generator.hpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp
  src/benchmarklib/tpch/tpch_table_generator.cpp
  src/benchmarklib/tpch/tpch_table_generator.hpp
  src/lib/CMakeLists.txt
  src/lib/expression/aggregate_expression.cpp
  src/lib/expression/aggregate_expression.hpp
  src/lib/expression/expression_utils.cpp
  src/lib/expression/expression_utils.hpp
  src/lib/expression/lqp_column_expression.cpp
  src/lib/logical_query_plan/abstract_lqp_node.hpp
  src/lib/logical_query_plan/join_node.hpp
  src/lib/logical_query_plan/lqp_column_reference.cpp
  src/lib/logical_query_plan/mock_node.cpp
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/strategy/column_pruning_rule.cpp
  src/lib/optimizer/strategy/column_pruning_rule.hpp
  src/lib/storage/constraints/table_constraint_definition.hpp
  src/lib/storage/table.cpp
  src/lib/storage/table.hpp
  src/lib/visualization/lqp_visualizer.cpp
  src/test/CMakeLists.txt
  src/test/expression/expression_test.cpp
  src/test/expression/expression_utils_test.cpp
  src/test/logical_query_plan/mock_node_test.cpp
  src/test/operators/insert_test.cpp
  src/test/optimizer/strategy/column_pruning_rule_test.cpp
  src/test/storage/constraints_test.cpp
Labels: FullCI

#1930 SQL keyword "table" as column name in meta manager
  resources/test_data/tbl/meta_tables/meta_chunks.tbl
  resources/test_data/tbl/meta_tables/meta_chunks_updated.tbl
  resources/test_data/tbl/meta_tables/meta_columns.tbl
  resources/test_data/tbl/meta_tables/meta_columns_updated.tbl
  resources/test_data/tbl/meta_tables/meta_segments.tbl
  resources/test_data/tbl/meta_tables/meta_segments_updated.tbl
  resources/test_data/tbl/meta_tables/meta_tables.tbl
  resources/test_data/tbl/meta_tables/meta_tables_updated.tbl
  src/lib/utils/meta_table_manager.cpp
  src/test/sql/sql_translator_test.cpp
  src/test/utils/meta_table_manager_test.cpp
Labels: FullCI, ReallyEasyToReview

#1931 Reference LQP node in PQP
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/operators/abstract_operator.hpp
  src/test/logical_query_plan/lqp_translator_test.cpp
Labels: FullCI

#1493 [DYOD18/19] MvccDeletePlugin with tests
  Jenkinsfile
  README.md
  src/lib/CMakeLists.txt
  src/lib/operators/alias_operator.cpp
  src/lib/operators/get_table.cpp
  src/lib/operators/insert.cpp
  src/lib/operators/projection.cpp
  src/lib/operators/validate.cpp
  src/lib/storage/chunk.cpp
  src/lib/storage/chunk.hpp
  src/lib/storage/table.cpp
  src/lib/storage/table.hpp
  src/lib/utils/abstract_plugin.hpp
  src/lib/utils/pausable_loop_thread.hpp
  src/lib/utils/plugin_manager.cpp
  src/lib/utils/plugin_manager.hpp
  src/plugins/CMakeLists.txt
  src/plugins/mvcc_delete_plugin.cpp
  src/plugins/mvcc_delete_plugin.hpp
  src/plugins/test_plugin.cpp
  src/plugins/test_plugin.hpp
  src/test/CMakeLists.txt
  src/test/concurrency/stress_test.cpp
  src/test/operators/insert_test.cpp
  src/test/operators/projection_test.cpp
  src/test/plugins/mvcc_delete_plugin_system_test.cpp
  src/test/plugins/mvcc_delete_plugin_test.cpp
  src/test/utils/singleton_test.cpp
Labels: FullCI

#1932 Retrieve access frequency of cached elements
  src/lib/cache/cache.hpp
  src/lib/cache/gdfs_cache.hpp
  src/lib/sql/sql_pipeline_builder.hpp
  src/test/cache/cache_test.cpp
Labels: FullCI

#1767 TPC-C
  Jenkinsfile
  README.md
  resources/test_data/tbl/int_float_updated.tbl
  scripts/test/hyriseBenchmarkFileBased_test.py
  scripts/test/hyriseBenchmarkJoinOrder_test.py
  scripts/test/hyriseBenchmarkTPCC_test.py
  scripts/test/hyriseBenchmarkTPCH_test.py
  scripts/test/hyriseConsole_test.py
  src/benchmark/CMakeLists.txt
  src/benchmark/tpcc_benchmark.cpp
  src/benchmarklib/CMakeLists.txt
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_sql_executor.cpp
  src/benchmarklib/benchmark_sql_executor.hpp
  src/benchmarklib/tpcc/procedures/abstract_tpcc_procedure.cpp
  src/benchmarklib/tpcc/procedures/abstract_tpcc_procedure.hpp
  src/benchmarklib/tpcc/procedures/tpcc_delivery.cpp
  src/benchmarklib/tpcc/procedures/tpcc_delivery.hpp
  src/benchmarklib/tpcc/procedures/tpcc_new_order.cpp
  src/benchmarklib/tpcc/procedures/tpcc_new_order.hpp
  src/benchmarklib/tpcc/procedures/tpcc_order_status.cpp
  src/benchmarklib/tpcc/procedures/tpcc_order_status.hpp
  src/benchmarklib/tpcc/procedures/tpcc_payment.cpp
  src/benchmarklib/tpcc/procedures/tpcc_payment.hpp
  src/benchmarklib/tpcc/procedures/tpcc_stock_level.cpp
  src/benchmarklib/tpcc/procedures/tpcc_stock_level.hpp
  src/benchmarklib/tpcc/tpcc_benchmark_item_runner.cpp
  src/benchmarklib/tpcc/tpcc_benchmark_item_runner.hpp
  src/benchmarklib/tpcc/tpcc_random_generator.hpp
  src/benchmarklib/tpcc/tpcc_table_generator.cpp
  src/benchmarklib/tpcc/tpcc_table_generator.hpp
  src/benchmarklib/tpch/tpch_table_generator.hpp
  src/bin/console/console.cpp
  src/bin/console/console.hpp
  src/lib/CMakeLists.txt
  src/lib/concurrency/transaction_context.cpp
  src/lib/concurrency/transaction_context.hpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/lib/storage/table.hpp
  src/lib/utils/sqlite_add_indices.cpp
  src/lib/utils/sqlite_wrapper.cpp
  src/lib/utils/sqlite_wrapper.hpp
  src/test/CMakeLists.txt
  src/test/benchmarklib/sqlite_add_indices_test.cpp
  src/test/operators/get_table_test.cpp
  src/test/optimizer/strategy/chunk_pruning_rule_test.cpp
  src/test/sql/sql_pipeline_statement_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
  src/test/sql/sqlite_testrunner/sqlite_wrapper_test.cpp
  src/test/storage/table_test.cpp
  src/test/tpc/tpcc_test.cpp
Labels: FullCI

#1934 SQLite test runner: Print line numbers
  src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner.hpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner_encodings.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner_unencoded.cpp
Labels: FullCI
