Repository hyrise/hyrise, pull requests merged in 2019-06, with the labels that each got.

#1697 IndexScan improvements
  src/lib/operators/index_scan.cpp
  src/test/operators/index_scan_test.cpp
Labels: FullCI

#1696 Add nullable column support to TableBuilder
  src/benchmarklib/CMakeLists.txt
  src/benchmarklib/abstract_table_generator.cpp
  src/benchmarklib/abstract_table_generator.hpp
  src/benchmarklib/table_builder.hpp
  src/benchmarklib/tpch/tpch_table_generator.cpp
  src/test/CMakeLists.txt
  src/test/benchmarklib/table_builder_test.cpp
Labels: FullCI, Masterprojekt

#1693 Allow reference to original column name with alias
  resources/test_data/sqlite_testrunner_queries.sql
  src/lib/sql/sql_identifier_resolver.cpp
  src/lib/sql/sql_identifier_resolver.hpp
  src/lib/sql/sql_translator.cpp
  src/lib/sql/sql_translator.hpp
  src/test/sql/sql_identifier_resolver_test.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI, Masterprojekt

#1707 Using MP fork for the TPC-DS standard query set
  .gitmodules
  DEPENDENCIES.md
Labels: FullCI, Masterprojekt, ReallyEasyToReview

#1713 Readme: fixes
  README.md
Labels: FullCI

#1719 Handle StaticTableNode in Cardinality Estimator
  src/lib/statistics/cardinality_estimator.cpp
  src/test/statistics/cardinality_estimator_test.cpp
Labels: FullCI

#1720 Visualize multiple LQPs/PQPs in one file
  src/benchmarklib/benchmark_sql_executor.cpp
Labels: FullCI

#1725 Show hash join's radix bits in PQP
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash.hpp
  src/test/operators/join_hash_test.cpp
Labels: FullCI

#1714 Small fixes and performance optimizations
  src/benchmarklib/benchmark_runner.cpp
  src/lib/expression/evaluation/like_matcher.hpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/storage/create_iterable_from_segment.hpp
  src/lib/storage/dictionary_segment.cpp
  src/lib/storage/dictionary_segment.hpp
  src/lib/storage/frame_of_reference_segment.cpp
  src/lib/storage/frame_of_reference_segment.hpp
  src/lib/storage/reference_segment/reference_segment_iterable.hpp
  src/lib/storage/run_length_segment.cpp
  src/lib/storage/run_length_segment.hpp
  src/lib/storage/value_segment.cpp
  src/lib/storage/value_segment.hpp
  src/lib/utils/string_utils.hpp
  src/test/operators/join_hash_steps_test.cpp
  src/test/operators/join_hash_test.cpp
  src/test/operators/join_hash_types_test.cpp
Labels: FullCI

#1727 JoinIndex support index on both sides
  src/lib/operators/join_index.cpp
  src/lib/operators/join_index.hpp
  src/test/operators/join_index_test.cpp
Labels: FullCI

#1728 Change Lambda captures to be compatible with C++20
  src/CMakeLists.txt
  src/lib/operators/index_scan.cpp
  src/lib/operators/table_scan.cpp
  src/lib/server/client_connection.cpp
  src/lib/server/server_session.cpp
  src/lib/server/task_runner.hpp
Labels: FullCI, ReallyEasyToReview

#1730 Remove function Table::chunks()
  src/benchmark/operators/table_scan_sorted_benchmark.cpp
  src/lib/operators/aggregate_sort.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/operators/sort.cpp
  src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp
  src/lib/storage/table.cpp
  src/lib/storage/table.hpp
  src/test/operators/index_scan_test.cpp
  src/test/operators/table_scan_between_test.cpp
  src/test/operators/table_scan_test.cpp
  src/test/optimizer/strategy/chunk_pruning_test.cpp
  src/test/storage/chunk_encoder_test.cpp
  src/test/storage/table_test.cpp
Labels: FullCI

#1731 TPC-H: Fix prepared statements
  src/benchmarklib/abstract_benchmark_item_runner.cpp
  src/benchmarklib/abstract_benchmark_item_runner.hpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.hpp
  src/test/tpc/tpch_test.cpp
Labels: FullCI, ReallyEasyToReview
