Repository hyrise/hyrise, pull requests merged in 2019-10, with the labels that each got.

#1859 Update column statistics when chunks are pruned
  src/lib/logical_query_plan/stored_table_node.hpp
  src/lib/optimizer/strategy/chunk_pruning_rule.cpp
  src/lib/optimizer/strategy/chunk_pruning_rule.hpp
  src/lib/statistics/attribute_statistics.cpp
  src/lib/statistics/attribute_statistics.hpp
  src/lib/statistics/base_attribute_statistics.cpp
  src/lib/statistics/base_attribute_statistics.hpp
  src/lib/statistics/cardinality_estimator.cpp
  src/lib/statistics/statistics_objects/abstract_histogram.cpp
  src/lib/statistics/statistics_objects/abstract_histogram.hpp
  src/lib/statistics/statistics_objects/abstract_statistics_object.cpp
  src/lib/statistics/statistics_objects/abstract_statistics_object.hpp
  src/test/CMakeLists.txt
  src/test/optimizer/strategy/chunk_pruning_rule_test.cpp
  src/test/statistics/statistics_objects/generic_histogram_test.cpp
Labels: FullCI

#1872 Fix TPC-DS 91, blacklist 88, add to CI
  Jenkinsfile
  resources/benchmark/tpcds/query_blacklist.cfg
  src/benchmarklib/benchmark_runner.cpp
  src/lib/statistics/statistics_objects/min_max_filter.cpp
  src/test/statistics/statistics_objects/min_max_filter_test.cpp
Labels: FullCI

#1876 Fix tmpfile handling in visualization
  src/lib/visualization/abstract_visualizer.hpp
Labels: FullCI

#1791 Reformulate OR to UNION
  resources/test_data/sqlite_testrunner_queries.sql
  src/benchmarklib/benchmark_runner.cpp
  src/lib/CMakeLists.txt
  src/lib/cost_estimation/abstract_cost_estimator.cpp
  src/lib/logical_query_plan/jit_aware_lqp_translator.hpp
  src/lib/logical_query_plan/lqp_utils.cpp
  src/lib/logical_query_plan/lqp_utils.hpp
  src/lib/optimizer/join_ordering/join_graph_builder.cpp
  src/lib/optimizer/join_ordering/join_graph_builder.hpp
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/strategy/between_composition_rule.cpp
  src/lib/optimizer/strategy/in_expression_rewrite_rule.cpp
  src/lib/optimizer/strategy/index_scan_rule.cpp
  src/lib/optimizer/strategy/index_scan_rule.hpp
  src/lib/optimizer/strategy/predicate_merge_rule.cpp
  src/lib/optimizer/strategy/predicate_merge_rule.hpp
  src/lib/optimizer/strategy/predicate_reordering_rule.cpp
  src/lib/optimizer/strategy/predicate_reordering_rule.hpp
  src/lib/optimizer/strategy/predicate_split_up_rule.cpp
  src/lib/optimizer/strategy/predicate_split_up_rule.hpp
  src/test/CMakeLists.txt
  src/test/optimizer/join_graph_builder_test.cpp
  src/test/optimizer/strategy/between_composition_rule_test.cpp
  src/test/optimizer/strategy/predicate_merge_rule_test.cpp
  src/test/optimizer/strategy/predicate_placement_rule_test.cpp
  src/test/optimizer/strategy/predicate_reordering_rule_test.cpp
  src/test/optimizer/strategy/predicate_split_up_rule_test.cpp
  src/test/optimizer/strategy/subquery_to_join_rule_test.cpp
  src/test/sql/sqlite_testrunner/sqlite_testrunner_jit.cpp
Labels: FullCI, Masterprojekt

#1879 Format compare_benchmarks.py output for Github
  scripts/compare_benchmarks.py
Labels: FullCI

#1884 Fix column vs column on strings
  resources/benchmark/tpcds/query_blacklist.cfg
  resources/test_data/sqlite_testrunner_queries.sql
  resources/test_data/tbl/sqlite/mixed_types_100.tbl
  src/lib/statistics/cardinality_estimator.cpp
Labels: FullCI, ReallyEasyToReview

#1887 Fix TPCH benchmark query list printout
  scripts/test/hyriseBenchmarkTPCH_test.py
  src/benchmark/tpch_benchmark.cpp
Labels: FullCI, ReallyEasyToReview

#1845 Upgrade to gcc-9
  CMakeLists.txt
  DEPENDENCIES.md
  Dockerfile
  Jenkinsfile
  cmake/FindFS.cmake
  cmake/git_watcher.cmake
  install.sh
  src/benchmarklib/abstract_benchmark_item_runner.cpp
  src/benchmarklib/abstract_benchmark_item_runner.hpp
  src/benchmarklib/benchmark_table_encoder.cpp
  src/benchmarklib/file_based_benchmark_item_runner.cpp
  src/benchmarklib/file_based_benchmark_item_runner.hpp
  src/benchmarklib/file_based_table_generator.cpp
  src/benchmarklib/tpcds/tpcds_table_generator.cpp
  src/benchmarklib/tpch/tpch_table_generator.cpp
  src/lib/CMakeLists.txt
  src/lib/cost_estimation/cost_estimator_logical.cpp
  src/lib/expression/arithmetic_expression.cpp
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/expression/function_expression.cpp
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/logical_query_plan/lqp_utils.hpp
  src/lib/operators/aggregate_hash.hpp
  src/lib/operators/join_nested_loop.cpp
  src/lib/operators/join_verification.cpp
  src/lib/operators/multi_predicate_join/multi_predicate_join_evaluator.cpp
  src/lib/operators/table_scan/column_like_table_scan_impl.cpp
  src/lib/operators/table_scan/column_vs_column_table_scan_impl.cpp
  src/lib/optimizer/strategy/expression_reduction_rule.cpp
  src/lib/optimizer/strategy/predicate_placement_rule.cpp
  src/lib/optimizer/strategy/subquery_to_join_rule.cpp
  src/lib/sql/sql_translator.cpp
  src/lib/statistics/cardinality_estimator.cpp
  src/lib/statistics/statistics_objects/abstract_histogram.cpp
  src/lib/storage/lz4_segment/lz4_encoder.hpp
  src/lib/storage/segment_encoding_utils.cpp
  src/lib/types.cpp
  src/lib/utils/ignore_unused_variable.hpp
  src/lib/utils/list_directory.cpp
  src/lib/utils/list_directory.hpp
  src/test/CMakeLists.txt
  src/test/logical_query_plan/lqp_utils_test.cpp
  third_party/CMakeLists.txt
  third_party/tpch-dbgen/CMakeLists.txt
Labels: FullCI

#1890 Correct two words in LQP utils
  src/lib/logical_query_plan/lqp_utils.hpp
Labels: FullCI, ReallyEasyToReview

#1888 Retire MPSM Join
  src/benchmark/operators/join_benchmark.cpp
  src/lib/CMakeLists.txt
  src/lib/operators/abstract_operator.hpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_mpsm.hpp
  src/lib/operators/join_mpsm/column_materializer_numa.hpp
  src/lib/operators/join_mpsm/radix_cluster_sort_numa.hpp
  src/test/CMakeLists.txt
  src/test/operators/join_mpsm_test.cpp
  src/test/operators/join_test_runner.cpp
  src/test/operators/operator_deep_copy_test.cpp
Labels: FullCI

#1900 Fix empty RangeFilter
  scripts/test/hyriseBenchmarkJoinOrder_test.py
  src/benchmarklib/benchmark_runner.cpp
  src/lib/scheduler/abstract_task.cpp
  src/lib/statistics/statistics_objects/range_filter.cpp
Labels: FullCI

#1819 New rule: Pre-Join Predicates
  Jenkinsfile
  scripts/compare_benchmarks.py
  src/lib/optimizer/strategy/predicate_placement_rule.cpp
  src/lib/optimizer/strategy/predicate_placement_rule.hpp
  src/lib/statistics/cardinality_estimator.cpp
  src/test/optimizer/strategy/predicate_placement_rule_test.cpp
  src/test/statistics/cardinality_estimator_test.cpp
Labels: FullCI

#1895 Verify TPC-DS query 88
  resources/benchmark/tpcds/query_blacklist.cfg
  resources/test_data/sqlite_testrunner_queries.sql
  src/lib/expression/aggregate_expression.cpp
  src/lib/expression/aggregate_expression.hpp
  src/lib/expression/expression_functional.cpp
  src/lib/expression/expression_functional.hpp
  src/lib/expression/lqp_column_expression.cpp
  src/lib/logical_query_plan/lqp_column_reference.cpp
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/operators/abstract_aggregate_operator.cpp
  src/lib/operators/abstract_aggregate_operator.hpp
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/aggregate_sort.cpp
  src/lib/operators/projection.cpp
  src/lib/optimizer/strategy/expression_reduction_rule.cpp
  src/lib/sql/sql_translator.cpp
  src/test/expression/expression_test.cpp
  src/test/operators/aggregate_test.cpp
  src/test/optimizer/strategy/expression_reduction_rule_test.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI, Masterprojekt

#1903 Ask to remove boost-1.67 in install script
  install.sh
Labels: FullCI

#1904 Fix table scan for clang 9 and AVX512 machines
  src/lib/operators/table_scan/abstract_table_scan_impl.hpp
Labels: FullCI, ReallyEasyToReview
