Repository hyrise/hyrise, pull requests merged in 2019-07, with the labels that each got.

#1726 Index sensitive column pruning
  src/lib/CMakeLists.txt
  src/lib/logical_query_plan/stored_table_node.cpp
  src/lib/logical_query_plan/stored_table_node.hpp
  src/lib/operators/get_table.cpp
  src/lib/operators/index_scan.hpp
  src/lib/operators/join_index.cpp
  src/lib/optimizer/strategy/index_scan_rule.cpp
  src/lib/optimizer/strategy/index_scan_rule.hpp
  src/lib/storage/chunk.cpp
  src/lib/storage/chunk.hpp
  src/lib/storage/index/base_index.hpp
  src/lib/storage/index/index_statistics.cpp
  src/lib/storage/index/index_statistics.hpp
  src/lib/storage/table.cpp
  src/lib/storage/table.hpp
  src/lib/utils/column_ids_after_pruning.cpp
  src/lib/utils/column_ids_after_pruning.hpp
  src/test/CMakeLists.txt
  src/test/logical_query_plan/stored_table_node_test.cpp
  src/test/operators/get_table_test.cpp
  src/test/operators/index_scan_test.cpp
  src/test/storage/chunk_test.cpp
  src/test/storage/multi_segment_index_test.cpp
  src/test/storage/single_segment_index_test.cpp
  src/test/utils/column_ids_after_pruning_test.cpp
Labels: FullCI

#1735 Fix assert message
  src/lib/operators/join_sort_merge.cpp
Labels: FullCI

#1732 More performance optimizations
  src/lib/cost_estimation/cost_estimator_logical.cpp
  src/lib/operators/aggregate_hash.hpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/optimizer/optimizer.cpp
  src/lib/storage/reference_segment.cpp
  src/lib/storage/reference_segment.hpp
  src/lib/storage/segment_accessor.cpp
  src/lib/storage/segment_accessor.hpp
Labels: FullCI

#1678 Binaries tests
  DEPENDENCIES.md
  Dockerfile
  Jenkinsfile
  install.sh
  resources/test_data/imdb_sample/aka_name.csv
  resources/test_data/imdb_sample/aka_name.csv.json
  resources/test_data/imdb_sample/aka_title.csv
  resources/test_data/imdb_sample/aka_title.csv.json
  resources/test_data/imdb_sample/cast_info.csv
  resources/test_data/imdb_sample/cast_info.csv.json
  resources/test_data/imdb_sample/char_name.csv
  resources/test_data/imdb_sample/char_name.csv.json
  resources/test_data/imdb_sample/comp_cast_type.csv
  resources/test_data/imdb_sample/comp_cast_type.csv.json
  resources/test_data/imdb_sample/company_name.csv
  resources/test_data/imdb_sample/company_name.csv.json
  resources/test_data/imdb_sample/company_type.csv
  resources/test_data/imdb_sample/company_type.csv.json
  resources/test_data/imdb_sample/complete_cast.csv
  resources/test_data/imdb_sample/complete_cast.csv.json
  resources/test_data/imdb_sample/info_type.csv
  resources/test_data/imdb_sample/info_type.csv.json
  resources/test_data/imdb_sample/keyword.csv
  resources/test_data/imdb_sample/keyword.csv.json
  resources/test_data/imdb_sample/kind_type.csv
  resources/test_data/imdb_sample/kind_type.csv.json
  resources/test_data/imdb_sample/link_type.csv
  resources/test_data/imdb_sample/link_type.csv.json
  resources/test_data/imdb_sample/movie_companies.csv
  resources/test_data/imdb_sample/movie_companies.csv.json
  resources/test_data/imdb_sample/movie_info.csv
  resources/test_data/imdb_sample/movie_info.csv.json
  resources/test_data/imdb_sample/movie_info_idx.csv
  resources/test_data/imdb_sample/movie_info_idx.csv.json
  resources/test_data/imdb_sample/movie_keyword.csv
  resources/test_data/imdb_sample/movie_keyword.csv.json
  resources/test_data/imdb_sample/movie_link.csv
  resources/test_data/imdb_sample/movie_link.csv.json
  resources/test_data/imdb_sample/name.csv
  resources/test_data/imdb_sample/name.csv.json
  resources/test_data/imdb_sample/person_info.csv
  resources/test_data/imdb_sample/person_info.csv.json
  resources/test_data/imdb_sample/role_type.csv
  resources/test_data/imdb_sample/role_type.csv.json
  resources/test_data/imdb_sample/title.csv
  resources/test_data/imdb_sample/title.csv.json
  resources/test_data/queries/file_based/select_statement.sql
  resources/test_data/tbl/file_based/test_table.tbl
  scripts/test/hyriseBenchmarkCore.py
  scripts/test/hyriseBenchmarkFileBased_test.py
  scripts/test/hyriseBenchmarkJoinOrder_test.py
  scripts/test/hyriseBenchmarkTPCH_test.py
  src/lib/statistics/statistics_objects/abstract_histogram.cpp
  src/test/statistics/statistics_objects/generic_histogram_test.cpp
Labels: FullCI

#1736 Fix benchmark_multithreaded.py
  scripts/benchmark_multithreaded.py
Labels: FullCI

#1737 Fix NUMA node binding
  src/lib/scheduler/topology.cpp
  src/lib/scheduler/topology.hpp
Labels: FullCI

#1738 Hash Join: improve offset calculation
  src/lib/operators/join_hash/join_hash_steps.hpp
Labels: FullCI

#1742 Corrected index support messages
  src/lib/operators/join_index.cpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_nested_loop.cpp
Labels: FullCI, ReallyEasyToReview

#1744 Benchmark: Warn about mismatching chunk sizes
  src/benchmarklib/abstract_table_generator.cpp
Labels: FullCI, ReallyEasyToReview

#1692 Allow "SELECT a AS a1, a AS a2..."
  resources/test_data/sqlite_testrunner_queries.sql
  src/lib/operators/aggregate_hash.hpp
  src/lib/sql/sql_identifier_resolver.cpp
  src/lib/sql/sql_identifier_resolver.hpp
  src/lib/sql/sql_translator.cpp
  src/lib/sql/sql_translator.hpp
  src/lib/statistics/join_graph_statistics_cache.cpp
  src/lib/storage/lqp_view.cpp
  src/lib/storage/lqp_view.hpp
  src/test/logical_query_plan/create_view_node_test.cpp
  src/test/operators/maintenance/create_view_test.cpp
  src/test/operators/maintenance/drop_view_test.cpp
  src/test/sql/sql_translator_test.cpp
  src/test/statistics/cardinality_estimator_test.cpp
  src/test/statistics/join_graph_statistics_cache_test.cpp
  src/test/statistics/statistics_objects/generic_histogram_test.cpp
  src/test/storage/storage_manager_test.cpp
Labels: FullCI, Masterprojekt

#1746 Make CreateViewNode debug info more informative
  src/lib/logical_query_plan/alias_node.cpp
  src/lib/logical_query_plan/create_view_node.cpp
  src/test/logical_query_plan/create_view_node_test.cpp
Labels: FullCI

#1749 Fix the master
  src/lib/logical_query_plan/create_view_node.cpp
Labels: FullCI

#1751 Mac: Fix build environment for jemalloc
  third_party/CMakeLists.txt
Labels: FullCI

#1747 Ensure that chunks added after LQP translation are handled
  resources/test_data/tbl/int_int_shuffled_appended_and_filtered.tbl
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/operators/index_scan.cpp
  src/lib/operators/index_scan.hpp
  src/lib/operators/table_scan.cpp
  src/lib/operators/table_scan.hpp
  src/test/logical_query_plan/lqp_translator_test.cpp
  src/test/operators/index_scan_test.cpp
  src/test/operators/table_scan_test.cpp
Labels: FullCI

#1752 Use UnionAll for combining Index- and TableScan results
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/operators/union_all.cpp
  src/lib/types.hpp
  src/test/logical_query_plan/lqp_translator_test.cpp
Labels: FullCI

#1756 Fix Union operator in index scan test
  src/test/operators/index_scan_test.cpp
Labels: FullCI

#1758 Upgrade to c++20
  src/CMakeLists.txt
Labels: FullCI, Performance, ReallyEasyToReview

#1743 Using indexes for index joins on reference tables
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/operators/abstract_join_operator.hpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash.hpp
  src/lib/operators/join_index.cpp
  src/lib/operators/join_index.hpp
  src/lib/operators/join_mpsm.cpp
  src/lib/operators/join_mpsm.hpp
  src/lib/operators/join_nested_loop.cpp
  src/lib/operators/join_nested_loop.hpp
  src/lib/operators/join_sort_merge.cpp
  src/lib/operators/join_sort_merge.hpp
  src/lib/operators/join_verification.cpp
  src/lib/operators/join_verification.hpp
  src/test/operators/join_index_test.cpp
  src/test/operators/join_test_runner.cpp
Labels: Feature, FullCI

#1763 Column pruning sensitive index scan
  src/lib/optimizer/strategy/index_scan_rule.cpp
  src/test/optimizer/strategy/index_scan_rule_test.cpp
Labels: FullCI, ReallyEasyToReview

#1759 TPC-C Preparation
  scripts/compare_benchmarks.py
  src/benchmark/tpch_benchmark.cpp
  src/benchmark/tpch_data_micro_benchmark.cpp
  src/benchmark/tpch_table_generator_benchmark.cpp
  src/benchmarklib/CMakeLists.txt
  src/benchmarklib/abstract_benchmark_item_runner.cpp
  src/benchmarklib/abstract_benchmark_item_runner.hpp
  src/benchmarklib/abstract_benchmark_table_generator.hpp
  src/benchmarklib/abstract_table_generator.cpp
  src/benchmarklib/abstract_table_generator.hpp
  src/benchmarklib/benchmark_config.cpp
  src/benchmarklib/benchmark_config.hpp
  src/benchmarklib/benchmark_item_result.cpp
  src/benchmarklib/benchmark_item_result.hpp
  src/benchmarklib/benchmark_item_run_result.cpp
  src/benchmarklib/benchmark_item_run_result.hpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_runner.hpp
  src/benchmarklib/benchmark_sql_executor.cpp
  src/benchmarklib/benchmark_sql_executor.hpp
  src/benchmarklib/cli_config_parser.cpp
  src/benchmarklib/file_based_benchmark_item_runner.cpp
  src/benchmarklib/file_based_benchmark_item_runner.hpp
  src/benchmarklib/tpcc/constants.hpp
  src/benchmarklib/tpcc/helper.cpp
  src/benchmarklib/tpcc/helper.hpp
  src/benchmarklib/tpcc/tpcc_random_generator.hpp
  src/benchmarklib/tpcc/tpcc_table_generator.cpp
  src/benchmarklib/tpcc/tpcc_table_generator.hpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp
  src/benchmarklib/tpch/tpch_benchmark_item_runner.hpp
  src/benchmarklib/tpch/tpch_table_generator.cpp
  src/benchmarklib/tpch/tpch_table_generator.hpp
  src/bin/console/console.cpp
  src/bin/console/console.hpp
  src/lib/expression/expression_utils.hpp
  src/lib/storage/frame_of_reference_segment.cpp
  src/test/tpc/tpch_db_generator_test.cpp
  src/test/tpc/tpch_test.cpp
Labels: FullCI

#1760 New plot script: Run duration over time
  requirements.txt
  scripts/plot_run_duration_over_time.py
Labels: FullCI

#1745 TableScan: Use type-specific implementations in more cases
  src/lib/CMakeLists.txt
  src/lib/operators/table_scan.cpp
  src/lib/operators/table_scan/abstract_dereferenced_column_table_scan_impl.cpp
  src/lib/operators/table_scan/abstract_dereferenced_column_table_scan_impl.hpp
  src/lib/operators/table_scan/column_between_table_scan_impl.cpp
  src/lib/operators/table_scan/column_between_table_scan_impl.hpp
  src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp
  src/lib/operators/table_scan/column_vs_value_table_scan_impl.hpp
  src/lib/types.cpp
  src/lib/types.hpp
  src/lib/utils/lossless_predicate_cast.cpp
  src/lib/utils/lossless_predicate_cast.hpp
  src/test/CMakeLists.txt
  src/test/operators/table_scan_test.cpp
  src/test/utils/lossless_predicate_cast_test.cpp
Labels: FullCI

#1715 Implement WITH queries
  src/lib/sql/sql_identifier_resolver_proxy.hpp
  src/lib/sql/sql_translator.cpp
  src/lib/sql/sql_translator.hpp
  src/lib/storage/prepared_plan.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI, Masterprojekt

#1686 Fix handling of nullptrs in calls of Table::get_chunk()
  src/benchmark/operators/join_benchmark.cpp
  src/benchmarklib/benchmark_table_encoder.cpp
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/operators/abstract_operator.cpp
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/alias_operator.cpp
  src/lib/operators/delete.cpp
  src/lib/operators/difference.cpp
  src/lib/operators/export_binary.cpp
  src/lib/operators/export_csv.cpp
  src/lib/operators/index_scan.cpp
  src/lib/operators/jit_operator/operators/jit_read_tuples.cpp
  src/lib/operators/jit_operator/operators/jit_validate.cpp
  src/lib/operators/jit_operator_wrapper.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/operators/join_index.cpp
  src/lib/operators/join_mpsm/column_materializer_numa.hpp
  src/lib/operators/join_nested_loop.cpp
  src/lib/operators/join_sort_merge/column_materializer.hpp
  src/lib/operators/limit.cpp
  src/lib/operators/multi_predicate_join/multi_predicate_join_evaluator.cpp
  src/lib/operators/print.cpp
  src/lib/operators/product.cpp
  src/lib/operators/projection.cpp
  src/lib/operators/sort.cpp
  src/lib/operators/table_scan.cpp
  src/lib/operators/table_scan/abstract_dereferenced_column_table_scan_impl.cpp
  src/lib/operators/table_scan/column_is_null_table_scan_impl.cpp
  src/lib/operators/union_all.cpp
  src/lib/operators/validate.cpp
  src/lib/optimizer/strategy/chunk_pruning_rule.cpp
  src/lib/server/query_response_builder.cpp
  src/lib/statistics/generate_pruning_statistics.cpp
  src/lib/storage/chunk_encoder.cpp
  src/lib/storage/reference_segment.cpp
  src/lib/storage/table.cpp
  src/lib/storage/table.hpp
  src/lib/tasks/chunk_compression_task.cpp
  src/lib/utils/load_table.cpp
  src/lib/utils/sqlite_wrapper.cpp
  src/test/operators/get_table_test.cpp
  src/test/operators/index_scan_test.cpp
  src/test/operators/jit_operator/operators/jit_write_reference_test.cpp
  src/test/operators/join_index_test.cpp
  src/test/storage/chunk_encoder_test.cpp
  src/test/storage/iterables_test.cpp
  src/test/storage/table_test.cpp
  src/test/tasks/chunk_compression_task_test.cpp
Labels: FullCI
