Repository hyrise/hyrise, pull requests merged in 2019-08, with the labels that each got.

#1775 [JIT] Fix bug #1741 - no support for COUNT(*) without group by
  resources/test_data/sqlite_testrunner_queries.sql
  src/lib/logical_query_plan/jit_aware_lqp_translator.cpp
  src/test/logical_query_plan/jit_aware_lqp_translator_test.cpp
Labels: Bug, FullCI

#1779 Fix SUBSTR and LIMIT in TPC-H queries
  resources/test_data/tbl/tpch/test-validation/q10.tbl
  resources/test_data/tbl/tpch/test-validation/q3.tbl
  resources/test_data/tbl/tpch/test-validation/q7.tbl
  resources/test_data/tbl/tpch/test-validation/q8.tbl
  resources/test_data/tbl/tpch/test-validation/q9.tbl
  resources/tpch_validation_queries.sql
  src/benchmarklib/tpch/tpch_queries.cpp
  src/test/tpc/tpch_test.cpp
Labels: FullCI

#1777 Fix handling of diamonds in placement rule
  src/lib/optimizer/strategy/predicate_placement_rule.cpp
  src/test/optimizer/strategy/predicate_placement_rule_test.cpp
Labels: FullCI

#1784 Fix sqlite comparison
  scripts/test/hyriseConsole_test.py
  src/lib/utils/check_table_equal.cpp
  src/lib/utils/check_table_equal.hpp
  src/lib/utils/sqlite_wrapper.cpp
Labels: FullCI

#1780 Add tests for random access iterators
  src/lib/storage/lz4_segment/lz4_segment_iterable.hpp
  src/test/storage/segment_iterators_test.cpp
Labels: FullCI

#1789 Disable TPC-DS Q85
  resources/benchmark/tpcds/query_blacklist.cfg
Labels: FullCI, ReallyEasyToReview

#1793 Enable executable TPC-DS WITH-queries
  resources/benchmark/tpcds/query_blacklist.cfg
Labels: FullCI, Masterprojekt, ReallyEasyToReview

#1801 CI: Store query plans as artifacts
  Jenkinsfile
  README.md
  scripts/test/hyriseBenchmarkTPCH_test.py
  src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp
Labels: FullCI

#1805 Small refactorings, mostly in the join
  src/benchmarklib/encoding_config.hpp
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/jit_operator/operators/jit_write_references.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/operators/join_index.cpp
  src/lib/operators/join_nested_loop.cpp
  src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp
  src/lib/optimizer/strategy/abstract_rule.hpp
  src/lib/optimizer/strategy/between_composition_rule.cpp
  src/lib/optimizer/strategy/between_composition_rule.hpp
  src/lib/optimizer/strategy/chunk_pruning_rule.cpp
  src/lib/optimizer/strategy/chunk_pruning_rule.hpp
  src/lib/optimizer/strategy/column_pruning_rule.cpp
  src/lib/optimizer/strategy/column_pruning_rule.hpp
  src/lib/optimizer/strategy/expression_reduction_rule.cpp
  src/lib/optimizer/strategy/expression_reduction_rule.hpp
  src/lib/optimizer/strategy/index_scan_rule.cpp
  src/lib/optimizer/strategy/index_scan_rule.hpp
  src/lib/optimizer/strategy/insert_limit_in_exists_rule.cpp
  src/lib/optimizer/strategy/insert_limit_in_exists_rule.hpp
  src/lib/optimizer/strategy/join_ordering_rule.cpp
  src/lib/optimizer/strategy/join_ordering_rule.hpp
  src/lib/optimizer/strategy/predicate_placement_rule.cpp
  src/lib/optimizer/strategy/predicate_placement_rule.hpp
  src/lib/optimizer/strategy/predicate_reordering_rule.cpp
  src/lib/optimizer/strategy/predicate_reordering_rule.hpp
  src/lib/optimizer/strategy/predicate_split_up_rule.cpp
  src/lib/optimizer/strategy/predicate_split_up_rule.hpp
  src/lib/optimizer/strategy/subquery_to_join_rule.cpp
  src/lib/optimizer/strategy/subquery_to_join_rule.hpp
  src/lib/storage/segment_iterables/segment_positions.hpp
  src/lib/types.cpp
  src/lib/types.hpp
  src/test/operators/jit_operator/operators/jit_read_write_tuple_test.cpp
  src/test/operators/jit_operator/operators/jit_validate_test.cpp
  src/test/operators/jit_operator/operators/jit_write_reference_test.cpp
  src/test/operators/join_hash_steps_test.cpp
  src/test/operators/join_test_runner.cpp
  src/test/operators/validate_test.cpp
  src/test/optimizer/optimizer_test.cpp
  src/test/storage/segment_iterators_test.cpp
Labels: FullCI

#1788 Meta tables
  resources/test_data/tbl/meta_tables/meta_chunks.tbl
  resources/test_data/tbl/meta_tables/meta_chunks_updated.tbl
  resources/test_data/tbl/meta_tables/meta_columns.tbl
  resources/test_data/tbl/meta_tables/meta_columns_updated.tbl
  resources/test_data/tbl/meta_tables/meta_segments.tbl
  resources/test_data/tbl/meta_tables/meta_segments_updated.tbl
  resources/test_data/tbl/meta_tables/meta_tables.tbl
  resources/test_data/tbl/meta_tables/meta_tables_updated.tbl
  src/lib/CMakeLists.txt
  src/lib/expression/lqp_column_expression.cpp
  src/lib/hyrise.hpp
  src/lib/logical_query_plan/abstract_lqp_node.hpp
  src/lib/logical_query_plan/lqp_translator.cpp
  src/lib/logical_query_plan/lqp_utils.cpp
  src/lib/logical_query_plan/show_columns_node.cpp
  src/lib/logical_query_plan/show_columns_node.hpp
  src/lib/logical_query_plan/show_tables_node.cpp
  src/lib/logical_query_plan/show_tables_node.hpp
  src/lib/operators/abstract_operator.hpp
  src/lib/operators/maintenance/show_columns.cpp
  src/lib/operators/maintenance/show_columns.hpp
  src/lib/operators/maintenance/show_tables.cpp
  src/lib/operators/maintenance/show_tables.hpp
  src/lib/optimizer/strategy/column_pruning_rule.cpp
  src/lib/sql/sql_translator.cpp
  src/lib/statistics/cardinality_estimator.cpp
  src/lib/storage/storage_manager.cpp
  src/lib/utils/meta_table_manager.cpp
  src/lib/utils/meta_table_manager.hpp
  src/lib/utils/sqlite_add_indices.cpp
  src/test/CMakeLists.txt
  src/test/logical_query_plan/lqp_find_subplan_mismatch_test.cpp
  src/test/logical_query_plan/lqp_translator_test.cpp
  src/test/logical_query_plan/show_columns_node_test.cpp
  src/test/logical_query_plan/show_tables_node_test.cpp
  src/test/operators/maintenance/show_columns_test.cpp
  src/test/operators/maintenance/show_tables_test.cpp
  src/test/sql/sql_translator_test.cpp
  src/test/statistics/cardinality_estimator_test.cpp
  src/test/storage/storage_manager_test.cpp
  src/test/utils/meta_table_manager_test.cpp
  src/test/utils/plugin_manager_test.cpp
Labels: FullCI

#1808 Remove erroneously committed micro benchmarks
  src/benchmark/tpch_data_micro_benchmark.cpp
Labels: FullCI

#1810 Fix predicate pushdown below diamond
  src/lib/logical_query_plan/base_non_query_node.hpp
  src/lib/optimizer/strategy/predicate_placement_rule.cpp
  src/test/optimizer/strategy/predicate_placement_rule_test.cpp
Labels: FullCI

#1807 Visualization: Make penwidths more reflective of cost
  src/benchmarklib/benchmark_config.hpp
  src/benchmarklib/cli_config_parser.cpp
  src/lib/CMakeLists.txt
  src/lib/utils/null_streambuf.cpp
  src/lib/utils/null_streambuf.hpp
  src/lib/visualization/abstract_visualizer.hpp
  src/lib/visualization/lqp_visualizer.cpp
  src/lib/visualization/pqp_visualizer.cpp
Labels: FullCI

#1802 Don't increase commit id for read-only transactions
  src/lib/concurrency/transaction_context.cpp
  src/lib/concurrency/transaction_context.hpp
  src/lib/operators/abstract_read_write_operator.cpp
  src/lib/operators/delete.cpp
  src/lib/operators/insert.cpp
  src/test/concurrency/transaction_context_test.cpp
  src/test/lib/hyrise_test.cpp
Labels: FullCI
