Repository hyrise/hyrise, pull requests merged in 2020-09, with the labels that each got.

#2205 Export meta table support for the console
  scripts/test/compareBenchmarkScriptTest.py
  src/bin/console/console.cpp
Labels: FullCI, ReallyEasyToReview

#2204 AggregateHash: Fix performance timer
  src/lib/operators/aggregate_hash.cpp
Labels: FullCI

#2206 benchmark_all: add TPCH SF .01
  scripts/benchmark_all.sh
Labels: FullCI

#2210 CsvParser: Finalize chunks of parsed table
  src/lib/import_export/csv/csv_parser.cpp
  src/test/lib/import_export/csv/csv_parser_test.cpp
Labels: FullCI, ReallyEasyToReview

#2195 JoinOrderingRule shortcut
  resources/test_data/tbl/meta_tables/meta_segments_accurate_libcpp_updated.tbl
  resources/test_data/tbl/meta_tables/meta_segments_accurate_libstdcpp_updated.tbl
  resources/test_data/tbl/meta_tables/meta_segments_libcpp_updated.tbl
  resources/test_data/tbl/meta_tables/meta_segments_libstdcpp_updated.tbl
  src/lib/optimizer/strategy/join_ordering_rule.cpp
Labels: FullCI

#2202 Hash Join: Merge output chunks <500 rows
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
Labels: FullCI

#2213 Fix pruning of PredicateNodes with multiple outputs
  resources/test_data/tbl/meta_tables/meta_segments_accurate_libcpp_updated.tbl
  resources/test_data/tbl/meta_tables/meta_segments_accurate_libstdcpp_updated.tbl
  resources/test_data/tbl/meta_tables/meta_segments_libcpp_updated.tbl
  resources/test_data/tbl/meta_tables/meta_segments_libstdcpp_updated.tbl
  src/lib/optimizer/strategy/chunk_pruning_rule.cpp
  src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp
Labels: FullCI

#2214 JoinHash: Move branch out of loop
  src/lib/operators/join_hash/join_hash_steps.hpp
Labels: FullCI

#2208 Refactor ColumnPruningRule to use LQP Unique Constraints
  src/lib/operators/table_scan.cpp
  src/lib/optimizer/strategy/column_pruning_rule.cpp
  src/test/lib/optimizer/strategy/column_pruning_rule_test.cpp
Labels: FullCI

#2218 Compression plugin change memory budget setting to mega byte
  src/lib/optimizer/strategy/subquery_to_join_rule.cpp
  src/lib/scheduler/node_queue_scheduler.cpp
  src/lib/statistics/cardinality_estimator.cpp
  src/lib/storage/vector_compression/simd_bp128/simd_bp128_decompressor.hpp
  src/plugins/clustering_plugin.cpp
  src/plugins/clustering_plugin.hpp
  src/plugins/compression_plugin.cpp
  src/plugins/compression_plugin.hpp
  src/plugins/index_selection_plugin.cpp
  src/plugins/index_selection_plugin.hpp
Labels: FullCI

#2215 Sort : keep nullable property for sorted segments
  src/lib/operators/sort.cpp
  src/test/lib/operators/sort_test.cpp
Labels: FullCI

#2224 _get_allocated_memory: Add comment about jemalloc allocation behavior
  src/lib/utils/meta_tables/meta_system_utilization_table.cpp
Labels: Documentation, FullCI

#2220 [Hyrise Cockpit] Add display name column to meta settings
  src/lib/utils/meta_tables/meta_settings_table.cpp
  src/lib/utils/settings/abstract_setting.hpp
  src/plugins/compression_plugin.hpp
  src/test/lib/sql/sql_translator_test.cpp
  src/test/lib/utils/meta_tables/meta_settings_table_test.cpp
  src/test/lib/utils/mock_setting.cpp
  src/test/lib/utils/mock_setting.hpp
Labels: FullCI

#2225 Add OperatorSteps to Projection
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/projection.cpp
  src/lib/operators/projection.hpp
Labels: FullCI

#2217 run_benchmarks_over_commit_range.sh: Some Fixes
  scripts/run_benchmarks_over_commit_range.sh
Labels: FullCI

#2221 Aggregate: Write ANY as part of grouping, not as pseudo aggregate function
  resources/test_data/tbl/aggregateoperator/groupby_int_1gb_0agg/result_any_null.tbl
  resources/test_data/tbl/aggregateoperator/groupby_int_1gb_1agg/any_filtered.tbl
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/operators/abstract_aggregate_operator.hpp
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/aggregate_hash.hpp
  src/lib/operators/aggregate_sort.cpp
  src/lib/optimizer/optimizer.cpp
  src/test/lib/operators/aggregate_test.cpp
Labels: FullCI

#2228 nullable Segment implies nullable column
  resources/test_data/bin/AllTypesAllNullValues/Unencoded.bin
  resources/test_data/bin/AllTypesNullValues/Unencoded.bin
  resources/test_data/bin/NullValuesFrameOfReferenceSegment.bin
  resources/test_data/bin/RunNullValues/Unencoded.bin
  src/lib/import_export/binary/binary_parser.cpp
  src/lib/import_export/binary/binary_parser.hpp
  src/lib/import_export/binary/binary_writer.cpp
  src/lib/import_export/binary/binary_writer.hpp
  src/lib/operators/abstract_operator.cpp
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/aggregate_sort.cpp
  src/test/lib/import_export/binary/binary_writer_test.cpp
  src/test/lib/operators/sort_test.cpp
Labels: FullCI
