Repository hyrise/hyrise, pull requests merged in 2020-05, with the labels that each got.

#2111 Stop SQLPipeline from leaking the SQLPipelineStatement(s)
  src/benchmark/operators/sql_benchmark.cpp
  src/lib/server/query_handler.cpp
  src/lib/sql/sql_pipeline.cpp
  src/lib/sql/sql_pipeline.hpp
  src/lib/sql/sql_pipeline_builder.cpp
  src/lib/sql/sql_pipeline_builder.hpp
  src/lib/sql/sql_pipeline_statement.cpp
  src/lib/sql/sql_pipeline_statement.hpp
  src/lib/sql/sql_translator.hpp
  src/test/logical_query_plan/lqp_translator_test.cpp
  src/test/operators/operator_deep_copy_test.cpp
  src/test/plugins/mvcc_delete_plugin_test.cpp
  src/test/server/query_handler_test.cpp
  src/test/sql/query_plan_cache_test.cpp
  src/test/sql/sql_pipeline_statement_test.cpp
  src/test/sql/sql_pipeline_test.cpp
Labels: FullCI

#2126 Reduce cache size in JoinTestRunner
  src/test/operators/join_test_runner.cpp
  src/test/tpc/tpch_db_generator_test.cpp
Labels: FullCI

#2122 Fix explanation in hash join
  src/lib/operators/join_hash.cpp
Labels: FullCI

#2125 Allow recognizing flipped JoinOperatorPredicates
  src/lib/operators/operator_join_predicate.cpp
  src/lib/operators/operator_join_predicate.hpp
  src/test/operators/operator_join_predicate_test.cpp
Labels: FullCI

#2120 Query plan visualization: use of thousands separators
  src/lib/visualization/abstract_visualizer.hpp
  src/lib/visualization/lqp_visualizer.cpp
  src/lib/visualization/pqp_visualizer.cpp
Labels: FullCI, ReallyEasyToReview

#2121 JoinIndex: Support Semi and Anti* joins with IndexSide::Left
  src/lib/operators/join_index.cpp
Labels: Feature, FullCI

#2044 System Information / Utilization Meta Tables
  src/lib/CMakeLists.txt
  src/lib/utils/meta_table_manager.cpp
  src/lib/utils/meta_tables/abstract_meta_table.hpp
  src/lib/utils/meta_tables/meta_system_information_table.cpp
  src/lib/utils/meta_tables/meta_system_information_table.hpp
  src/lib/utils/meta_tables/meta_system_utilization_table.cpp
  src/lib/utils/meta_tables/meta_system_utilization_table.hpp
  src/test/CMakeLists.txt
  src/test/utils/meta_table_manager_test.cpp
  src/test/utils/meta_tables/meta_system_utilization_test.cpp
Labels: FullCI

#2127 Console: Horizontal Scrolling
  src/bin/console/console.cpp
  src/bin/console/pagination.cpp
  src/bin/console/pagination.hpp
Labels: FullCI

#2108 Remove ccache from CI
  Dockerfile
  Jenkinsfile
  README.md
  install_dependencies.sh
Labels: FullCI

#2133 Fix Export Column Pruning
  resources/test_data/bin/int_float.bin
  resources/test_data/bin/int_float_deleted.bin
  resources/test_data/bin/int_float_deleted.csv
  resources/test_data/bin/int_float_deleted.csv.json
  src/lib/optimizer/strategy/column_pruning_rule.cpp
  src/test/optimizer/strategy/column_pruning_rule_test.cpp
  src/test/server/server_test_runner.cpp
Labels: FullCI

#2129 Remove unused Cache Implementations
  scripts/test/hyriseConsole_test.py
  src/lib/CMakeLists.txt
  src/lib/cache/abstract_cache.hpp
  src/lib/cache/abstract_cache_impl.hpp
  src/lib/cache/cache.hpp
  src/lib/cache/gdfs_cache.hpp
  src/lib/cache/gds_cache.hpp
  src/lib/cache/lru_cache.hpp
  src/lib/cache/lru_k_cache.hpp
  src/lib/cache/random_cache.hpp
  src/lib/sql/sql_pipeline_statement.hpp
  src/lib/sql/sql_plan_cache.hpp
  src/test/base_test.cpp
  src/test/base_test.hpp
  src/test/cache/cache_test.cpp
  src/test/concurrency/stress_test.cpp
  src/test/server/server_test_runner.cpp
  src/test/sql/query_plan_cache_test.cpp
  src/test/sql/sql_pipeline_statement_test.cpp
Labels: FullCI

#2117 Fix two expression issues
  resources/test_data/sqlite_testrunner_queries.sql
  src/lib/operators/table_scan.cpp
  src/lib/sql/sql_translator.cpp
  src/test/operators/table_scan_test.cpp
  src/test/sql/sql_translator_test.cpp
Labels: FullCI

#2135 Change ValueExpression long suffix to upper case
  src/lib/expression/value_expression.cpp
Labels: FullCI

#2118 Console: Use proper transaction handling
  scripts/test/hyriseConsole_test.py
  src/bin/console/console.cpp
  src/bin/console/console.hpp
Labels: FullCI

#2136 StoredTableColumnAlignmentRule
  src/lib/CMakeLists.txt
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/strategy/stored_table_column_alignment_rule.cpp
  src/lib/optimizer/strategy/stored_table_column_alignment_rule.hpp
  src/test/CMakeLists.txt
  src/test/optimizer/strategy/stored_table_column_alignment_rule_test.cpp
Labels: Feature, FullCI, Performance

#2110 Remove NULLS LAST mode
  resources/test_data/tbl/sort/a_asc_b_desclast.tbl
  resources/test_data/tbl/sort/b_asclast_a_asc.tbl
  resources/test_data/tbl/sort/c_asc_b_desclast.tbl
  src/lib/operators/sort.cpp
  src/lib/operators/table_scan/sorted_segment_search.hpp
  src/lib/storage/chunk.cpp
  src/lib/storage/chunk.hpp
  src/lib/types.cpp
  src/lib/types.hpp
  src/test/benchmarklib/tpcc/tpcc_test.cpp
  src/test/lib/logical_query_plan/lqp_translator_test.cpp
  src/test/lib/logical_query_plan/sort_node_test.cpp
  src/test/lib/operators/sort_test.cpp
  src/test/lib/operators/table_scan_between_test.cpp
  src/test/lib/operators/table_scan_sorted_segment_search_test.cpp
  src/test/lib/operators/table_scan_test.cpp
  src/test/lib/storage/chunk_test.cpp
Labels: FullCI

#2139 Console: Streamline exception handling
  scripts/test/hyriseConsole_test.py
  src/bin/console/console.cpp
Labels: FullCI

#2078 Functional Dependencies & Rewrite of DependentGroupByReductionRule
  GLOSSARY.md
  src/lib/CMakeLists.txt
  src/lib/expression/abstract_expression.hpp
  src/lib/logical_query_plan/abstract_lqp_node.cpp
  src/lib/logical_query_plan/abstract_lqp_node.hpp
  src/lib/logical_query_plan/functional_dependency.cpp
  src/lib/logical_query_plan/functional_dependency.hpp
  src/lib/logical_query_plan/mock_node.cpp
  src/lib/logical_query_plan/mock_node.hpp
  src/lib/logical_query_plan/stored_table_node.cpp
  src/lib/logical_query_plan/stored_table_node.hpp
  src/lib/logical_query_plan/union_node.cpp
  src/lib/logical_query_plan/union_node.hpp
  src/lib/operators/abstract_join_operator.hpp
  src/lib/operators/index_scan.cpp
  src/lib/optimizer/strategy/dependent_group_by_reduction_rule.cpp
  src/lib/optimizer/strategy/dependent_group_by_reduction_rule.hpp
  src/lib/storage/index/abstract_index.hpp
  src/lib/storage/index/group_key/group_key_index.hpp
  src/lib/storage/table.cpp
  src/test/lib/logical_query_plan/alias_node_test.cpp
  src/test/lib/logical_query_plan/join_node_test.cpp
  src/test/lib/logical_query_plan/stored_table_node_test.cpp
  src/test/lib/logical_query_plan/union_node_test.cpp
  src/test/lib/optimizer/strategy/dependent_group_by_reduction_rule_test.cpp
Labels: FullCI

#2140 Clarify join predicate order
  src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp
  src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.hpp
  src/lib/optimizer/join_ordering/dp_ccp.hpp
  src/lib/optimizer/join_ordering/greedy_operator_ordering.hpp
  src/lib/optimizer/strategy/join_ordering_rule.hpp
  src/lib/optimizer/strategy/join_predicate_ordering_rule.hpp
Labels: FullCI

#2146 Clarify benchmark information text
  scripts/test/hyriseBenchmarkFileBased_test.py
  scripts/test/hyriseBenchmarkJoinOrder_test.py
  scripts/test/hyriseBenchmarkTPCH_test.py
  src/benchmarklib/cli_config_parser.cpp
Labels: FullCI

#2145 Cleanup optimizer tests
  src/test/lib/optimizer/strategy/predicate_placement_rule_test.cpp
  src/test/lib/optimizer/strategy/predicate_reordering_rule_test.cpp
Labels: FullCI
