Repository hyrise/hyrise, pull requests merged in 2021-01, with the labels that each got.

#2279 Add null scan removal rule
  src/lib/CMakeLists.txt
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/strategy/null_scan_removal_rule.cpp
  src/lib/optimizer/strategy/null_scan_removal_rule.hpp
  src/test/CMakeLists.txt
  src/test/lib/optimizer/strategy/null_scan_removal_rule_test.cpp
Labels: FullCI

#2290 AggregateHash: Cache result ids
  src/lib/operators/aggregate_hash.cpp
  src/lib/operators/aggregate_hash.hpp
Labels: FullCI

#2300 Finalize chunks in AbstractTableGenerator before setting sortedness information
  src/benchmarklib/abstract_table_generator.cpp
Labels: FullCI

#2294 JoinHash: Improve PosList handling of hash map bigly
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/test/lib/operators/join_hash/join_hash_steps_test.cpp
  src/test/lib/operators/join_hash/join_hash_types_test.cpp
Labels: FullCI

#2296 Enable M1 builds
  CMakeLists.txt
  cmake/FindReadline.cmake
  src/lib/all_type_variant.hpp
  src/lib/statistics/attribute_statistics.hpp
  src/lib/statistics/statistics_objects/abstract_histogram.hpp
  src/lib/statistics/statistics_objects/generic_histogram.hpp
  src/lib/statistics/statistics_objects/generic_histogram_builder.hpp
  src/lib/statistics/statistics_objects/min_max_filter.hpp
  src/lib/statistics/statistics_objects/range_filter.hpp
  src/lib/storage/dictionary_segment.cpp
  src/lib/storage/dictionary_segment.hpp
  src/lib/storage/fixed_string_dictionary_segment.hpp
  src/lib/storage/frame_of_reference_segment.hpp
  src/lib/storage/index/b_tree/b_tree_index_impl.hpp
  src/lib/storage/lz4_segment.hpp
  src/lib/storage/run_length_segment.cpp
  src/lib/storage/run_length_segment.hpp
  src/lib/storage/segment_accessor.hpp
  src/lib/storage/value_segment.cpp
  src/lib/storage/value_segment.hpp
Labels: FullCI

#2287 Add threshold for parallel execution in table scan and join hash
  src/lib/operators/join_hash.hpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/lib/operators/table_scan.cpp
Labels: FullCI

#2298 Allow benchmark data generation in hyrise server
  Jenkinsfile
  scripts/test/compareBenchmarkScriptTest.py
  scripts/test/hyriseServer_test.py
  src/benchmarklib/cli_config_parser.cpp
  src/bin/CMakeLists.txt
  src/bin/server.cpp
Labels: FullCI

#2304 Build on Raspberry Pi 4
  CMakeLists.txt
Labels: DevOps, FullCI, ReallyEasyToReview

#2302 Add performance measuring to join sort merge
  README.md
  src/lib/operators/join_hash.hpp
  src/lib/operators/join_sort_merge.cpp
  src/lib/operators/join_sort_merge.hpp
  src/lib/operators/join_sort_merge/radix_cluster_sort.hpp
Labels: FullCI

#2305 Override destructor in segment accessors (clang11)
  src/lib/storage/segment_accessor.hpp
Labels: FullCI, ReallyEasyToReview

#2308 Fix Jenkins, allow admin override
  Jenkinsfile
Labels: FullCI

#2309 Update README.md
  README.md
Labels: FullCI

#2310 Fix Jenkins 2.0
  Jenkinsfile
Labels: FullCI
