Repository hyrise/hyrise, pull requests merged in 2021-04, with the labels that each got.

#2347 Fix OperatorsDeleteTest.UseTransactionContextAfterCommit
  src/lib/operators/abstract_read_write_operator.cpp
  src/test/lib/operators/delete_test.cpp
Labels: FullCI, ReallyEasyToReview

#2341 Update Contributor guidelines
  CONTRIBUTING.md
  LICENSE
  README.md
  src/lib/expression/evaluation/expression_evaluator.cpp
Labels: FullCI

#2349 Fix JoinTestRunner
  src/test/lib/operators/join_test_runner.cpp
Labels: FullCI

#2354 Jenkinsfile: Use credentials for docker.com
  Jenkinsfile
Labels: FullCI

#2353 BenchmarkRunner: Write report idempotently
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_runner.hpp
Labels: FullCI

#2357 Streamline Boost includes
  scripts/benchmark_all.sh
  src/benchmarklib/synthetic_table_generator.cpp
  src/benchmarklib/table_builder.hpp
  src/lib/all_parameter_variant.cpp
  src/lib/all_type_variant.cpp
  src/lib/cache/gdfs_cache.hpp
  src/lib/expression/abstract_expression.cpp
  src/lib/expression/abstract_predicate_expression.cpp
  src/lib/expression/aggregate_expression.cpp
  src/lib/expression/arithmetic_expression.cpp
  src/lib/expression/between_expression.cpp
  src/lib/expression/binary_predicate_expression.cpp
  src/lib/expression/case_expression.hpp
  src/lib/expression/correlated_parameter_expression.cpp
  src/lib/expression/evaluation/expression_evaluator.hpp
  src/lib/expression/evaluation/expression_result.hpp
  src/lib/expression/evaluation/like_matcher.cpp
  src/lib/expression/function_expression.cpp
  src/lib/expression/logical_expression.cpp
  src/lib/expression/lqp_column_expression.cpp
  src/lib/expression/lqp_subquery_expression.cpp
  src/lib/expression/placeholder_expression.cpp
  src/lib/expression/pqp_column_expression.cpp
  src/lib/expression/value_expression.cpp
  src/lib/hyrise.hpp
  src/lib/import_export/file_type.cpp
  src/lib/logical_query_plan/abstract_lqp_node.cpp
  src/lib/logical_query_plan/alias_node.cpp
  src/lib/logical_query_plan/functional_dependency.cpp
  src/lib/logical_query_plan/mock_node.hpp
  src/lib/null_value.hpp
  src/lib/operators/aggregate_hash.hpp
  src/lib/operators/aggregate_sort.hpp
  src/lib/operators/alias_operator.cpp
  src/lib/operators/table_scan/column_like_table_scan_impl.hpp
  src/lib/optimizer/join_ordering/join_graph_edge.hpp
  src/lib/sql/create_sql_parser_error_message.cpp
  src/lib/statistics/cardinality_estimator.hpp
  src/lib/statistics/join_graph_statistics_cache.hpp
  src/lib/statistics/statistics_objects/abstract_histogram.cpp
  src/lib/storage/table.hpp
  src/lib/type_comparison.hpp
  src/lib/utils/boost_bimap_core_override.hpp
  src/lib/utils/load_table.cpp
  src/lib/visualization/viz_record_layout.hpp
Labels: FullCI, Refactor

#2356 Exclude correlated subqueries from diamond shapes
  src/lib/expression/correlated_parameter_expression.cpp
  src/lib/expression/placeholder_expression.cpp
  src/lib/logical_query_plan/lqp_translator.cpp
  src/test/lib/expression/expression_test.cpp
  src/test/lib/logical_query_plan/lqp_translator_test.cpp
Labels: FullCI

#2345 Hash join: keep track of skipped values from Bloom filtering
  scripts/plot_operator_breakdown.py
  scripts/test/compareBenchmarkScriptTest.py
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash.hpp
  src/lib/operators/join_hash/join_hash_steps.hpp
  src/test/lib/operators/operator_performance_data_test.cpp
Labels: FullCI

#2360 Move definition of JoinHash::calculate_radix_bits() to .hpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash.hpp
Labels: FullCI

#2359 Markus' retirement
  README.md
Labels: FullCI
