Repository hyrise/hyrise, pull requests merged in 2021-09, with the labels that each got.

#2400 Prettier Visualizer plans with consistent label wrapping & updated operator descriptions
  src/lib/operators/abstract_aggregate_operator.cpp
  src/lib/operators/abstract_join_operator.cpp
  src/lib/operators/alias_operator.cpp
  src/lib/operators/get_table.cpp
  src/lib/operators/join_hash.cpp
  src/lib/operators/join_hash.hpp
  src/lib/operators/join_index.cpp
  src/lib/operators/table_scan.cpp
  src/lib/operators/table_scan.hpp
  src/lib/visualization/abstract_visualizer.hpp
  src/test/lib/operators/join_hash_test.cpp
  src/test/lib/operators/join_index_test.cpp
  src/test/lib/operators/join_nested_loop_test.cpp
  src/test/lib/operators/join_sort_merge_test.cpp
  src/test/lib/operators/join_verification_test.cpp
Labels: Refactor, FullCI

#2403 Use the scheduler for controlled data preparation parallelism
  scripts/test/compareBenchmarkScriptTest.py
  src/benchmarklib/abstract_table_generator.cpp
  src/benchmarklib/benchmark_config.cpp
  src/benchmarklib/benchmark_config.hpp
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_table_encoder.cpp
  src/benchmarklib/cli_config_parser.cpp
  src/lib/statistics/table_statistics.cpp
Labels: Feature, FullCI

#2396 [DYOD] Cardinality estimation: selectivity calculation
  src/lib/statistics/cardinality_estimator.cpp
  src/test/lib/statistics/cardinality_estimator_test.cpp
Labels: FullCI

#2405 Adjust benchmark_all.sh to allow faster benchmark cycles
  Jenkinsfile
  scripts/benchmark_all.sh
  scripts/compare_benchmarks.py
  src/benchmark/tpcds_benchmark.cpp
Labels: FullCI

#2408 Complement InRewriteRule's auto approach
  src/lib/optimizer/strategy/in_expression_rewrite_rule.cpp
  src/lib/optimizer/strategy/in_expression_rewrite_rule.hpp
  src/test/lib/optimizer/strategy/in_expression_rewrite_rule_test.cpp
Labels: FullCI
