Repository hyrise/hyrise, pull requests merged in 2022-11, with the labels that each got.

#2512 Fix binary export of reference segments and enable coverage generation on macOS
  resources/test_data/bin/AllTypesReferenceSegment.bin
  scripts/coverage.sh
  src/lib/import_export/binary/binary_writer.cpp
  src/lib/import_export/binary/binary_writer.hpp
  src/test/lib/import_export/binary/binary_writer_test.cpp
Labels: ReallyEasyToReview, FullCI

#2485 [DYOD] UCC Discovery Plugin
  .gitignore
  README.md
  resources/test_data/tbl/uniqueness_test_A.tbl
  resources/test_data/tbl/uniqueness_test_B.tbl
  src/lib/storage/pos_lists/entire_chunk_pos_list.hpp
  src/plugins/CMakeLists.txt
  src/plugins/ucc_discovery_plugin.cpp
  src/plugins/ucc_discovery_plugin.hpp
  src/test/CMakeLists.txt
  src/test/plugins/mvcc_delete_plugin_test.cpp
  src/test/plugins/ucc_discovery_plugin_test.cpp
Labels: FullCI

#2516 Google Benchmark as System Lib: Clarify Comment
  src/benchmark/CMakeLists.txt
Labels: ReallyEasyToReview, FullCI

#2517 Document that Warming up Benchmark Queries Caches the Plans
  src/benchmarklib/benchmark_runner.cpp
  src/benchmarklib/benchmark_runner.hpp
Labels: Documentation, ReallyEasyToReview, FullCI

#2486 [DYOD] Join to Local Predicate Rewrite Rule
  scripts/benchmark_multithreaded.py
  scripts/compare_benchmarks.py
  scripts/compare_benchmarks_multithreaded.py
  src/CMakeLists.txt
  src/lib/CMakeLists.txt
  src/lib/logical_query_plan/join_node.cpp
  src/lib/logical_query_plan/join_node.hpp
  src/lib/logical_query_plan/mock_node.cpp
  src/lib/optimizer/optimizer.cpp
  src/lib/optimizer/strategy/column_pruning_rule.cpp
  src/lib/optimizer/strategy/column_pruning_rule.hpp
  src/lib/optimizer/strategy/join_to_predicate_rewrite_rule.cpp
  src/lib/optimizer/strategy/join_to_predicate_rewrite_rule.hpp
  src/lib/optimizer/strategy/join_to_semi_join_rule.cpp
  src/lib/optimizer/strategy/join_to_semi_join_rule.hpp
  src/test/CMakeLists.txt
  src/test/lib/optimizer/strategy/column_pruning_rule_test.cpp
  src/test/lib/optimizer/strategy/join_to_predicate_rewrite_rule_test.cpp
  src/test/lib/optimizer/strategy/join_to_semi_join_rule_test.cpp
  src/test/lib/storage/chunk_encoder_test.cpp
Labels: FullCI

#2511 Clang 15 support
  src/lib/operators/join_helper/join_output_writing.hpp
  src/lib/types.hpp
  src/lib/utils/size_estimation_utils.hpp
Labels: ReallyEasyToReview, FullCI
