Repository hyrise/hyrise, pull requests merged in 2022-05, with the labels that each got.

#2447 Allow predicate pushdown through Union diamonds
  src/lib/logical_query_plan/lqp_utils.cpp
  src/lib/logical_query_plan/lqp_utils.hpp
  src/lib/optimizer/strategy/predicate_placement_rule.cpp
  src/test/lib/logical_query_plan/lqp_utils_test.cpp
  src/test/lib/optimizer/strategy/predicate_placement_rule_test.cpp
Labels: FullCI

#2456 Refactor EnableMakeForLQPNode
  src/lib/logical_query_plan/enable_make_for_lqp_node.hpp
Labels: Refactor, FullCI

#2466 Deep-Copy LQP node comments
  src/lib/cost_estimation/abstract_cost_estimator.cpp
  src/lib/cost_estimation/abstract_cost_estimator.hpp
  src/lib/logical_query_plan/abstract_lqp_node.cpp
  src/lib/statistics/statistics_objects/generic_histogram.hpp
  src/test/lib/logical_query_plan/mock_node_test.cpp
Labels: ReallyEasyToReview, FullCI

#2461 Support for GCC 11 and small fix
  Jenkinsfile
  scripts/benchmark_multithreaded.py
  scripts/compare_benchmarks_multithreaded.py
  src/lib/cache/gdfs_cache.hpp
  src/lib/operators/join_sort_merge.cpp
  src/lib/operators/table_scan/abstract_table_scan_impl.hpp
  src/lib/storage/storage_manager.hpp
Labels: FullCI

#2469 Fix Casting of string `NULL` Values
  resources/test_data/tbl/string_numbers_null.tbl
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/test/lib/expression/expression_evaluator_to_values_test.cpp
Labels: Bug, ReallyEasyToReview, FullCI
