Repository hyrise/hyrise, pull requests merged in 2023-02, with the labels that each got.

#2520 Schedule uncorrelated subqueries together with other operators
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/expression/evaluation/expression_evaluator.hpp
  src/lib/operators/abstract_operator.cpp
  src/lib/operators/abstract_operator.hpp
  src/lib/operators/projection.cpp
  src/lib/operators/projection.hpp
  src/lib/operators/table_scan.cpp
  src/lib/operators/table_scan.hpp
  src/lib/operators/table_scan/expression_evaluator_table_scan_impl.cpp
  src/lib/operators/table_scan/expression_evaluator_table_scan_impl.hpp
  src/lib/scheduler/abstract_task.cpp
  src/lib/scheduler/abstract_task.hpp
  src/lib/scheduler/operator_task.cpp
  src/lib/scheduler/operator_task.hpp
  src/test/lib/expression/expression_evaluator_to_pos_list_test.cpp
  src/test/lib/expression/expression_evaluator_to_values_test.cpp
  src/test/lib/operators/operator_clear_output_test.cpp
  src/test/lib/operators/table_scan_test.cpp
  src/test/lib/scheduler/operator_task_test.cpp
Labels: Bug, FullCI

#2535 Remove dummy table output from maintenance operators
  src/lib/operators/abstract_operator.cpp
  src/lib/operators/maintenance/create_table.cpp
  src/lib/operators/maintenance/create_view.cpp
  src/lib/operators/maintenance/drop_table.cpp
  src/lib/operators/maintenance/drop_view.cpp
  src/test/lib/operators/maintenance/create_table_test.cpp
  src/test/lib/operators/maintenance/create_view_test.cpp
  src/test/lib/operators/maintenance/drop_table_test.cpp
  src/test/lib/operators/maintenance/drop_view_test.cpp
Labels: ReallyEasyToReview, FullCI

#2538 Remove Boost overrides
  scripts/lint.sh
  src/lib/CMakeLists.txt
  src/lib/all_type_variant.hpp
  src/lib/storage/encoding_type.hpp
  src/lib/storage/vector_compression/compressed_vector_type.hpp
  src/lib/types.hpp
  src/lib/utils/boost_bimap_core_override.hpp
  src/lib/utils/boost_curry_override.hpp
Labels: ReallyEasyToReview, FullCI

#2531 Avoid coverage badge caching and change info text
  README.md
  scripts/test/hyriseServer_test.py
  src/benchmarklib/abstract_table_generator.cpp
  src/lib/storage/reference_segment/reference_segment_iterable.hpp
Labels: FullCI

#2541 Prune tables regardless of predicates with subqueries
  src/lib/optimizer/strategy/chunk_pruning_rule.cpp
  src/lib/optimizer/strategy/chunk_pruning_rule.hpp
  src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp
  src/test/lib/sql/sql_translator_test.cpp
Labels: FullCI

#2547 Rename `BetweenExpression` and `InExpression`s' `value()` to `operand()`
  src/benchmarklib/encoding_config.cpp
  src/benchmarklib/synthetic_table_generator.cpp
  src/benchmarklib/table_builder.hpp
  src/lib/expression/between_expression.cpp
  src/lib/expression/between_expression.hpp
  src/lib/expression/evaluation/expression_evaluator.cpp
  src/lib/expression/in_expression.cpp
  src/lib/expression/in_expression.hpp
  src/lib/operators/abstract_operator.cpp
  src/lib/operators/aggregate_sort.cpp
  src/lib/operators/table_scan.cpp
  src/lib/optimizer/strategy/in_expression_rewrite_rule.cpp
  src/lib/optimizer/strategy/subquery_to_join_rule.cpp
  src/lib/server/postgres_protocol_handler.cpp
  src/lib/server/result_serializer.cpp
  src/lib/sql/sql_translator.cpp
  src/lib/statistics/cardinality_estimator.cpp
  src/lib/statistics/join_graph_statistics_cache.cpp
  src/lib/statistics/statistics_objects/range_filter.cpp
  src/plugins/mvcc_delete_plugin.cpp
  src/test/lib/expression/evaluation/like_matcher_test.cpp
  src/test/lib/operators/import_test.cpp
  src/test/lib/operators/join_hash/join_hash_types_test.cpp
  src/test/lib/operators/table_scan_test.cpp
  src/test/lib/optimizer/strategy/column_pruning_rule_test.cpp
  src/test/lib/server/transaction_handling_test.cpp
  src/test/lib/storage/storage_manager_test.cpp
Labels: ReallyEasyToReview, FullCI

#2544 Parallelize Join Output Writing
  scripts/compare_benchmarks.py
  src/lib/CMakeLists.txt
  src/lib/operators/join_helper/join_output_writing.cpp
  src/lib/operators/join_helper/join_output_writing.hpp
Labels: FullCI
