Repository hyrise/hyrise, pull requests merged in 2024-12, with the labels that each got.

#2666 Parallelize loading of benchmark data
  scripts/test/hyriseBenchmarkTPCC_test.py
  scripts/test/hyriseBenchmarkTPCH_test.py
  src/benchmarklib/abstract_table_generator.cpp
  src/benchmarklib/file_based_table_generator.cpp
Labels: ReallyEasyToReview, FullCI

#2665 Console: Restore default settings during `reset`
  scripts/test/hyriseConsole_test.py
  src/bin/console/console.cpp
  src/bin/console/console.hpp
Labels: ReallyEasyToReview, FullCI

#2668 Exchange `imdb_data.zip` and change its host
  scripts/setup_imdb.py
Labels: Bug, FullCI

#2674 Small changes to `.gitignore` and an error message in `setup_imdb.py`
  .gitignore
  scripts/setup_imdb.py
Labels: FullCI
