Repository hyrise/hyrise, pull requests merged in 2025-02, with the labels that each got.

#2682 Minor fixes in cardinality estimation
  resources/test_data/sqlite_testrunner_queries.sql
  src/lib/statistics/cardinality_estimator.cpp
  src/test/lib/statistics/cardinality_estimator_test.cpp
Labels: Bug, ReallyEasyToReview, FullCI

#2686 Remove llvm-symbolizer from Dockerfile
  Dockerfile
Labels: DevOps, ReallyEasyToReview, FullCI

#2687 Fix `install_dependencies.sh`
  install_dependencies.sh
Labels: FullCI
